import * as THREE from 'three';

export function createVolumetricAtmosphere({scene,camera,layers=12,radius=110,height=26}={}){
  const actualLayers=Math.min(layers,10),group=new THREE.Group(),mats=[],geo=new THREE.PlaneGeometry(radius*2,radius*2);
  for(let i=0;i<actualLayers;i++){const depth=i/Math.max(1,actualLayers-1),mat=new THREE.ShaderMaterial({transparent:true,depthWrite:false,depthTest:true,blending:THREE.NormalBlending,side:THREE.DoubleSide,uniforms:{uTime:{value:0},uDepth:{value:depth},uDensity:{value:.012+depth*.009},uFogColor:{value:new THREE.Color().setHSL(.53,.23,.13+depth*.035)},uCamera:{value:camera.position}},vertexShader:`varying vec3 vWorld;void main(){vec4 w=modelMatrix*vec4(position,1.0);vWorld=w.xyz;gl_Position=projectionMatrix*viewMatrix*w;}`,fragmentShader:`varying vec3 vWorld;uniform float uTime,uDepth,uDensity;uniform vec3 uFogColor,uCamera;float h(vec2 p){p=fract(p*vec2(127.1,311.7));p+=dot(p,p+19.19);return fract(p.x*p.y);}float n(vec2 p){vec2 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(h(i),h(i+vec2(1,0)),f.x),mix(h(i+vec2(0,1)),h(i+1.),f.x),f.y);}float fbm(vec2 p){float v=0.,a=.5;for(int i=0;i<3;i++){v+=a*n(p);p=p*2.03+17.7;a*=.5;}return v;}void main(){float dist=distance(vWorld.xz,uCamera.xz);float radial=1.-smoothstep(48.,115.,dist);float f=fbm(vWorld.xz*.028+vec2(uTime*.004,-uTime*.002)+uDepth*23.);float pockets=smoothstep(.3,.76,f);float layer=smoothstep(.02,.22,uDepth)*smoothstep(1.,.62,uDepth);float density=uDensity*(.28+pockets*.72)*radial*layer;gl_FragColor=vec4(uFogColor,density);}`});const plane=new THREE.Mesh(geo,mat);plane.rotation.x=-Math.PI/2;plane.position.y=-1+depth*height;group.add(plane);mats.push(mat);}
  const shaftGroup=new THREE.Group(),shaftMat=new THREE.MeshBasicMaterial({color:0xc8e9ff,transparent:true,opacity:.025,blending:THREE.AdditiveBlending,depthWrite:false,side:THREE.DoubleSide,toneMapped:false});
  for(let i=0;i<5;i++){const shaft=new THREE.Mesh(new THREE.ConeGeometry(2.0+i*.22,20+i*1.7,16,1,true),shaftMat.clone());shaft.position.set(-24+i*11,11,-14-i*3);shaft.rotation.z=.22;shaft.rotation.x=-.08;shaftGroup.add(shaft);}scene.add(group,shaftGroup);
  return{group,shaftGroup,update(dt,time){group.position.x=camera.position.x;group.position.z=camera.position.z;shaftGroup.position.x=camera.position.x*.18;shaftGroup.position.z=camera.position.z*.18;for(const m of mats)m.uniforms.uTime.value=time;for(let i=0;i<shaftGroup.children.length;i++){const s=shaftGroup.children[i];s.material.opacity=.018+.012*(.5+.5*Math.sin(time*.14+i));}}};
}
