import * as THREE from 'three';

export class SpatialAudioSystem{
  constructor(camera,{occlusionTest=null}={}){
    this.camera=camera;this.listener=new THREE.AudioListener();camera.add(this.listener);this.ctx=this.listener.context;this.occlusionTest=occlusionTest;this.started=false;this.combatIntensity=0;
    this.master=this.ctx.createGain();this.master.gain.value=.78;
    this.compressor=this.ctx.createDynamicsCompressor();this.compressor.threshold.value=-16;this.compressor.knee.value=18;this.compressor.ratio.value=3.2;this.compressor.attack.value=.005;this.compressor.release.value=.16;
    this.limiter=this.ctx.createDynamicsCompressor();this.limiter.threshold.value=-2;this.limiter.knee.value=0;this.limiter.ratio.value=18;this.limiter.attack.value=.001;this.limiter.release.value=.055;
    this.master.connect(this.compressor).connect(this.limiter).connect(this.ctx.destination);
    this.music=this.#bus(.15);this.ambience=this.#bus(.27);this.combat=this.#bus(.82);this.ui=this.#bus(.5);
    this.reverb=this.ctx.createConvolver();this.reverb.buffer=this.#impulseResponse(1.15,2.6);this.reverbWet=this.ctx.createGain();this.reverbWet.gain.value=.16;this.reverb.connect(this.reverbWet).connect(this.master);
  }
  #bus(value){const g=this.ctx.createGain();g.gain.value=value;g.connect(this.master);return g;}
  setOcclusionTest(fn){this.occlusionTest=fn;}
  async unlock(){if(this.ctx.state!=='running')await this.ctx.resume();if(!this.started){this.started=true;this.#startAmbience();}}
  setCombatIntensity(value,dt=.016){this.combatIntensity=THREE.MathUtils.damp(this.combatIntensity,THREE.MathUtils.clamp(value,0,1),4.5,dt);const t=this.ctx.currentTime;this.music.gain.cancelScheduledValues(t);this.ambience.gain.cancelScheduledValues(t);this.music.gain.linearRampToValueAtTime(.13+this.combatIntensity*.075,t+.1);this.ambience.gain.linearRampToValueAtTime(.28-this.combatIntensity*.11,t+.1);}
  #duck(amount=.14,duration=.16){const t=this.ctx.currentTime,targets=[[this.music,.13],[this.ambience,.24]];for(const[g,base]of targets){const current=Math.max(.025,g.gain.value);g.gain.cancelScheduledValues(t);g.gain.setValueAtTime(current,t);g.gain.linearRampToValueAtTime(Math.max(.025,current-amount),t+.012);g.gain.exponentialRampToValueAtTime(Math.max(.03,base),t+duration);}}
  playWhoosh(position,power=1){if(!this.started)return;const now=this.ctx.currentTime,src=this.ctx.createBufferSource();src.buffer=this.#noiseBuffer(.19);const band=this.ctx.createBiquadFilter();band.type='bandpass';band.frequency.setValueAtTime(1550,now);band.frequency.exponentialRampToValueAtTime(310,now+.17);band.Q.value=.62;const gain=this.ctx.createGain();gain.gain.setValueAtTime(.0001,now);gain.gain.exponentialRampToValueAtTime(.23*power,now+.015);gain.gain.exponentialRampToValueAtTime(.0001,now+.18);const spatial=this.#spatial(position);src.connect(band).connect(gain).connect(spatial.input);spatial.output.connect(this.combat);spatial.output.connect(this.#send(.055));src.start(now);
    const o=this.ctx.createOscillator(),og=this.ctx.createGain();o.type='sine';o.frequency.setValueAtTime(210,now);o.frequency.exponentialRampToValueAtTime(78,now+.13);og.gain.setValueAtTime(.0001,now);og.gain.exponentialRampToValueAtTime(.055*power,now+.009);og.gain.exponentialRampToValueAtTime(.0001,now+.15);o.connect(og).connect(spatial.input);o.start(now);o.stop(now+.16);}
  playImpact(position,power=1){if(!this.started)return;this.#duck(.12*power,.19);const now=this.ctx.currentTime,spatial=this.#spatial(position),src=this.ctx.createBufferSource();src.buffer=this.#noiseBuffer(.24);const low=this.ctx.createBiquadFilter();low.type='lowpass';low.frequency.setValueAtTime(950,now);low.frequency.exponentialRampToValueAtTime(260,now+.19);const g=this.ctx.createGain();g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime(.34*power,now+.004);g.gain.exponentialRampToValueAtTime(.0001,now+.21);src.connect(low).connect(g).connect(spatial.input);spatial.output.connect(this.combat);spatial.output.connect(this.#send(.12));src.start(now);
    for(const[f,amp,type]of[[108,.14,'triangle'],[54,.11,'sine'],[420,.025,'square']]){const o=this.ctx.createOscillator(),og=this.ctx.createGain();o.type=type;o.frequency.setValueAtTime(f,now);o.frequency.exponentialRampToValueAtTime(Math.max(32,f*.52),now+.17);og.gain.setValueAtTime(amp*power,now);og.gain.exponentialRampToValueAtTime(.0001,now+.2);o.connect(og).connect(spatial.input);o.start(now);o.stop(now+.21);}}
  playRift(position,power=1){if(!this.started)return;this.#duck(.085*power,.42);const now=this.ctx.currentTime,spatial=this.#spatial(position);spatial.output.connect(this.combat);spatial.output.connect(this.#send(.2));for(const[f,detune]of[[68,-8],[104,5],[205,-3],[308,7]]){const o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=f<120?'sawtooth':'sine';o.frequency.setValueAtTime(f,now);o.detune.value=detune;o.frequency.exponentialRampToValueAtTime(f*1.72,now+.52);g.gain.setValueAtTime(.0001,now);g.gain.exponentialRampToValueAtTime((f<120?.034:.022)*power,now+.045);g.gain.exponentialRampToValueAtTime(.0001,now+.68);o.connect(g).connect(spatial.input);o.start(now);o.stop(now+.7);}const shimmer=this.ctx.createBufferSource();shimmer.buffer=this.#noiseBuffer(.62);const high=this.ctx.createBiquadFilter();high.type='highpass';high.frequency.value=1800;const sg=this.ctx.createGain();sg.gain.setValueAtTime(.0001,now);sg.gain.exponentialRampToValueAtTime(.03*power,now+.12);sg.gain.exponentialRampToValueAtTime(.0001,now+.62);shimmer.connect(high).connect(sg).connect(spatial.input);shimmer.start(now);}
  #spatial(position){const p=this.ctx.createPanner();p.panningModel='HRTF';p.distanceModel='inverse';p.refDistance=1.7;p.maxDistance=62;p.rolloffFactor=1.18;p.positionX.value=position.x;p.positionY.value=position.y;p.positionZ.value=position.z;const occlusion=this.occlusionTest?THREE.MathUtils.clamp(this.occlusionTest(this.camera.position,position)||0,0,1):0,filter=this.ctx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=THREE.MathUtils.lerp(18000,1150,occlusion);filter.Q.value=.55;p.connect(filter);return{input:p,output:filter};}
  #send(amount){const g=this.ctx.createGain();g.gain.value=amount;g.connect(this.reverb);return g;}
  #noiseBuffer(duration){const len=Math.max(32,Math.floor(this.ctx.sampleRate*duration)),b=this.ctx.createBuffer(1,len,this.ctx.sampleRate),d=b.getChannelData(0);let last=0;for(let i=0;i<len;i++){const white=Math.random()*2-1;last=last*.68+white*.32;d[i]=last;}return b;}
  #impulseResponse(duration,decay){const len=Math.floor(this.ctx.sampleRate*duration),b=this.ctx.createBuffer(2,len,this.ctx.sampleRate);for(let c=0;c<2;c++){const d=b.getChannelData(c);for(let i=0;i<len;i++)d[i]=(Math.random()*2-1)*Math.pow(1-i/len,decay)*(c?0.92:1);}return b;}
  #startAmbience(){const now=this.ctx.currentTime,noise=this.ctx.createBufferSource();noise.buffer=this.#noiseBuffer(5);noise.loop=true;const filter=this.ctx.createBiquadFilter();filter.type='lowpass';filter.frequency.value=840;const g=this.ctx.createGain();g.gain.value=.12;noise.connect(filter).connect(g).connect(this.ambience);noise.start(now);const wind=this.ctx.createBufferSource();wind.buffer=this.#noiseBuffer(6);wind.loop=true;const band=this.ctx.createBiquadFilter();band.type='bandpass';band.frequency.value=340;band.Q.value=.35;const wg=this.ctx.createGain();wg.gain.value=.055;wind.connect(band).connect(wg).connect(this.ambience);wind.start(now);for(const f of[43,64]){const o=this.ctx.createOscillator(),dg=this.ctx.createGain();o.type='sine';o.frequency.value=f;dg.gain.value=f===43?.012:.006;o.connect(dg).connect(this.ambience);o.start(now);}}
}
