import * as THREE from 'three';
import { GLTFLoader } from 'three/addons/loaders/GLTFLoader.js';

const PROFILE_URL='/assets/authored/character-source.json';
const FALLBACK_PROFILE={schemaVersion:2,target:'high-end OSRS/07Scape',tier:'quaternius-dressed-intermediate',provider:'Quaternius CC0',visualAcceptanceEligible:false,clothingComplete:true,actors:{hero:{url:'/assets/authored/quaternius-dressed/Male_Ranger.gltf',label:'Vanguard / Quaternius Ranger dressed body',height:2.48,bulk:1.04,animationUrls:['/assets/authored/quaternius-dressed/UAL1.glb','/assets/authored/quaternius-dressed/UAL-Combat-Extension.glb'],clothingComplete:true,silhouetteClass:'hooded-ranger-vanguard',palette:'weathered-forest-bronze',equipment:[]},enemy:{url:'/assets/authored/quaternius-dressed/Female_Ranger.gltf',label:'Dread Warden / Quaternius Ranger armored variant',height:2.72,bulk:1.13,animationUrls:['/assets/authored/quaternius-dressed/UAL1.glb','/assets/authored/quaternius-dressed/UAL-Combat-Extension.glb'],clothingComplete:true,silhouetteClass:'helmeted-heavy-warden',palette:'charcoal-oxblood-iron',equipment:[]}}};
const STATE_KEYWORDS={idle:[['idle','loop'],['idle'],['standing']],walk:[['walk','loop'],['walk'],['walking']],run:[['jog','fwd'],['jog'],['run'],['running']],sprint:[['sprint'],['run'],['jog']],attack:[['sword','attack'],['punch','cross'],['melee'],['attack'],['slash'],['swing']],rift:[['spell','simple','shoot'],['spell'],['cast']],guard:[['idle','shield'],['shield'],['guard'],['block'],['defend']],parry:[['idle','shield'],['shield'],['parry'],['block']],dodge:[['roll'],['slide','start'],['slide'],['dodge'],['evade']],hit:[['hit','chest'],['hit','head'],['hit'],['damage'],['hurt']],death:[['death01'],['death'],['die'],['dead']],turnLeft:[['turn','left']],turnRight:[['turn','right']],enemyIdle:[['idle','loop'],['idle'],['standing']],enemyWalk:[['walk','loop'],['walk'],['walking']],enemyRun:[['jog','fwd'],['jog'],['run'],['running']],enemyAttack:[['melee','hook'],['sword','attack'],['punch','cross'],['melee'],['attack']],enemyHeavy:[['melee','hook'],['hook'],['heavy'],['punch','cross']],enemyHit:[['hit','chest'],['hit','head'],['hit']],enemyStagger:[['hit','knockback'],['knockback'],['stagger'],['hit']],enemyDeath:[['death01'],['death'],['die'],['dead']]};
const ONCE=new Set(['attack','rift','parry','dodge','hit','death','enemyAttack','enemyHeavy','enemyHit','enemyStagger','enemyDeath']);
const PALETTES={
  'weathered-forest-bronze':{skin:0xb88762,cloth:0xb69c67,leather:0x604a32,accent:0x667b55,metal:0x9e906f},
  'charcoal-oxblood-iron':{skin:0xa87566,cloth:0x62585a,leather:0x3e3031,accent:0x6b2831,metal:0x706f6c}
};
const clean=s=>String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const loader=new GLTFLoader(),gltfCache=new Map();let profilePromise=null;
function loadGltf(url){if(!gltfCache.has(url))gltfCache.set(url,loader.loadAsync(url).catch(error=>{gltfCache.delete(url);throw error;}));return gltfCache.get(url);}
function loadProfile(){if(profilePromise)return profilePromise;profilePromise=fetch(PROFILE_URL,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(`character source profile ${r.status}`);return r.json();}).catch(()=>FALLBACK_PROFILE);return profilePromise;}
function scoreClip(name,terms){const n=clean(name);let score=0;for(const term of terms){if(!n.includes(term))return-1;score+=term.length*4;}if(n===terms.join(' '))score+=30;return score-n.length*.03;}
function resolveClip(clips,state){const patterns=STATE_KEYWORDS[state]||STATE_KEYWORDS.idle;let winner=null,best=-Infinity;for(let p=0;p<patterns.length;p++)for(const clip of clips){const score=scoreClip(clip.name,patterns[p])-p*12;if(score>best){best=score;winner=clip;}}return best>=0?winner:null;}
function materialDirection(material,paletteName,meshName=''){
  if(!material)return material;
  const m=material.clone(),p=PALETTES[paletteName],materialName=clean(material.name),n=clean(`${material.name} ${meshName}`);
  if('roughness'in m)m.roughness=.82;if('metalness'in m)m.metalness=0;if('envMapIntensity'in m)m.envMapIntensity=.22;if('clearcoat'in m)m.clearcoat=0;
  if(m.map){m.map=null;m.needsUpdate=true;}if(m.normalMap)m.normalMap=null;if(m.roughnessMap)m.roughnessMap=null;if(m.metalnessMap)m.metalnessMap=null;if(m.aoMap)m.aoMap=null;
  if(p&&m.color){
    let tint=p.cloth;
    if(materialName.includes('regular')||materialName.includes('skin'))tint=p.skin;
    if(n.includes('belt')||n.includes('boot')||n.includes('bracer')||n.includes('club')||n.includes('wood'))tint=p.leather;
    else if(n.includes('pauldron')||n.includes('metal')||n.includes('helmet')||n.includes('sword')||n.includes('blade')||n.includes('weapon')||n.includes('axe'))tint=p.metal;
    else if(n.includes('hood')||n.includes('accent'))tint=p.accent;
    m.color.setHex(tint);
  }
  m.needsUpdate=true;return m;
}
function tuneAndMeasure(model,palette){let triangles=0,meshes=0,skinnedMeshes=0,materials=0;const seenMaterials=new Set();model.traverse(o=>{if(!o.isMesh)return;meshes++;if(o.isSkinnedMesh)skinnedMeshes++;o.castShadow=true;o.receiveShadow=true;o.frustumCulled=true;if(Array.isArray(o.material))o.material=o.material.map(m=>materialDirection(m,palette,o.name));else o.material=materialDirection(o.material,palette,o.name);const mats=Array.isArray(o.material)?o.material:[o.material];for(const m of mats)if(m&&!seenMaterials.has(m)){seenMaterials.add(m);materials++;}const g=o.geometry;if(g){const count=g.index?.count??g.attributes?.position?.count??0;triangles+=Math.floor(count/3);}});return{triangles,meshes,skinnedMeshes,materials};}
function normalizeModel(model,targetHeight,bulk){model.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(model),size=box.getSize(new THREE.Vector3());if(!Number.isFinite(size.y)||size.y<.01)throw new Error(`Invalid authored character bounds ${size.y}`);const scale=targetHeight/size.y;model.scale.set(scale*bulk,scale,scale*bulk);model.updateMatrixWorld(true);const normalized=new THREE.Box3().setFromObject(model);model.position.y-=normalized.min.y;model.updateMatrixWorld(true);return{sourceHeight:size.y,targetHeight,scale};}
function captureLegacyMeshes(root){const meshes=[];root.traverse(o=>{if(o.isMesh&&!o.userData?.authoredCharacter)meshes.push(o);});return meshes;}
function suppressLegacyMeshes(list){for(const mesh of list){mesh.userData.hiddenByAuthoredCharacter=true;mesh.visible=false;}}
function countVisible(list){return list.reduce((n,o)=>n+(o.visible?1:0),0);}
function hideNamedMeshes(model,names=[]){const hidden=[];for(const wanted of names){const target=model.getObjectByName(wanted);if(target){target.visible=false;target.userData.hiddenByOutfitComposition=true;hidden.push(wanted);}}return hidden;}
function findBone(model,name){let exact=null,fuzzy=null;const wanted=clean(name);model.traverse(o=>{if(!o.isBone)return;if(!exact&&o.name===name)exact=o;if(!fuzzy&&clean(o.name)===wanted)fuzzy=o;});return exact||fuzzy;}
async function loadAnimationClips(urls=[]){const sources=[],byName=new Map();for(const url of urls){const gltf=await loadGltf(url),names=(gltf.animations||[]).map(c=>c.name);sources.push({url,clips:names});for(const clip of gltf.animations||[])if(clip?.name&&!byName.has(clip.name))byName.set(clip.name,clip);}return{sources,clips:[...byName.values()]};}
async function installEquipment(model,equipment=[],paletteName){
  return Promise.all(equipment.map(async spec=>{
    const gltf=await loadGltf(spec.url),gear=gltf.scene.clone(true);gear.name=`AuthoredEquipment:${spec.name}`;gear.userData.authoredCharacter=true;gear.userData.authoredEquipment=true;
    const metrics=tuneAndMeasure(gear,paletteName),box=new THREE.Box3().setFromObject(gear),size=box.getSize(new THREE.Vector3()),longest=Math.max(size.x,size.y,size.z,.001),weapon=/sword|club|axe|staff/i.test(spec.name),targetLongest=weapon?.92:.52,uniform=targetLongest/longest*(Number(spec.rootScale)||1);gear.scale.setScalar(uniform);
    const bone=findBone(model,spec.bone);if(!bone)throw new Error(`Equipment ${spec.name} missing target bone ${spec.bone}`);bone.add(gear);
    gear.position.set(...(weapon?[0,-.02,.01]:[0,.02,0]));gear.rotation.set(...(weapon?[-Math.PI/2,0,0]:[0,0,0]));if(/club/i.test(spec.name))gear.rotation.z=.18;if(/helmet/i.test(spec.name)){gear.rotation.set(0,0,0);gear.position.set(0,.04,0);}gear.updateMatrixWorld(true);
    return{name:spec.name,url:spec.url,bone:bone.name,triangles:metrics.triangles,meshes:metrics.meshes,targetLongest,sourceLongest:+longest.toFixed(3)};
  }));
}
function makeActor(role,root){
  const status={role,source:null,url:null,sourceTier:null,provider:null,visualAcceptanceEligible:false,clothingComplete:false,silhouetteClass:null,palette:null,ready:false,installed:false,error:null,loadingStage:'created',stageStartedAt:performance.now(),loadMs:null,clips:[],clipMap:{},animationSources:[],equipment:[],hiddenMeshes:[],triangles:0,meshes:0,skinnedMeshes:0,materials:0,visibleProceduralMeshes:0,currentState:null,currentClip:null};
  const legacy=captureLegacyMeshes(root);let mixer=null,currentAction=null,model=null,clips=[];const stage=name=>{status.loadingStage=name;status.stageStartedAt=performance.now();};
  const load=(async()=>{const started=performance.now();try{
    stage('profile');const profile=await loadProfile(),source=profile?.actors?.[role]||FALLBACK_PROFILE.actors[role];status.source=source.label;status.url=source.url;status.sourceTier=profile.tier||'unknown';status.provider=profile.provider||'unknown';status.visualAcceptanceEligible=profile.visualAcceptanceEligible===true;status.clothingComplete=source.clothingComplete===true&&profile.clothingComplete!==false;status.silhouetteClass=source.silhouetteClass||null;status.palette=source.palette||null;if(!status.clothingComplete)throw new Error(`${role} source tier is under-clothed; nude/base-body presentation forbidden`);
    stage('model');const gltf=await loadGltf(source.url);model=gltf.scene;status.hiddenMeshes=hideNamedMeshes(model,source.hiddenMeshes||[]);
    stage('animations');const external=await loadAnimationClips(source.animationUrls||[]),all=new Map();for(const clip of [...(gltf.animations||[]),...external.clips])if(clip?.name&&!all.has(clip.name))all.set(clip.name,clip);clips=[...all.values()];status.animationSources=external.sources;
    stage('install');model.name=role==='hero'?'VanguardAuthoredPresentation':'WardenAuthoredPresentation';model.userData.authoredCharacter=true;model.userData.license='CC0-1.0';model.userData.sourceTier=status.sourceTier;model.userData.clothingComplete=true;const metrics=tuneAndMeasure(model,source.palette),normalization=normalizeModel(model,source.height,source.bulk);root.add(model);
    stage('equipment');status.equipment=await installEquipment(model,source.equipment||[],source.palette);suppressLegacyMeshes(legacy);mixer=new THREE.AnimationMixer(model);status.clips=clips.map(c=>c.name);for(const state of Object.keys(STATE_KEYWORDS)){const clip=resolveClip(clips,state);if(clip)status.clipMap[state]=clip.name;}
    Object.assign(status,metrics,{normalization,ready:true,installed:true,visibleProceduralMeshes:countVisible(legacy),loadingStage:'ready',loadMs:Math.round((performance.now()-started)*10)/10});return status;
  }catch(error){status.ready=true;status.loadingStage='error';status.loadMs=Math.round((performance.now()-started)*10)/10;status.error=String(error?.message||error);return status;}})();
  function setState(state,speed=0){if(!mixer||!model||!status.installed)return;const clipName=status.clipMap[state]||status.clipMap.idle;if(!clipName)return;if(status.currentState===state&&currentAction)return;const actual=clips.find(c=>c.name===clipName);if(!actual)return;const next=mixer.clipAction(actual);next.enabled=true;next.clampWhenFinished=ONCE.has(state);next.setLoop(ONCE.has(state)?THREE.LoopOnce:THREE.LoopRepeat,ONCE.has(state)?1:Infinity);next.reset();const locomotion=['walk','run','sprint','enemyWalk','enemyRun'].includes(state),isWalk=state==='walk'||state==='enemyWalk';next.timeScale=locomotion?THREE.MathUtils.clamp((speed||1)/(isWalk?2.5:5.2),.72,1.42):1;next.fadeIn(currentAction?.isRunning?.()?.07:.02).play();if(currentAction&&currentAction!==next)currentAction.fadeOut(.09);currentAction=next;status.currentState=state;status.currentClip=actual.name;}
  function update(dt,state,speed){if(mixer){setState(state,speed);mixer.update(dt);}suppressLegacyMeshes(legacy);status.visibleProceduralMeshes=countVisible(legacy);}
  return{status,load,update,get model(){return model;}};
}
export function installAuthoredActor(root,role){if(!root||!FALLBACK_PROFILE.actors[role])throw new Error(`Invalid authored actor ${role}`);return makeActor(role,root);}
export function installAuthoredCharacterPresentation({heroRig,enemyRig}){const hero=installAuthoredActor(heroRig.group,'hero'),enemy=installAuthoredActor(enemyRig.group,'enemy'),status={target:'high-end OSRS/07Scape',ready:false,accepted:false,hero:hero.status,enemy:enemy.status,error:null};const ready=Promise.all([hero.load,enemy.load]).then(()=>{status.ready=true;const errors=[hero.status.error,enemy.status.error].filter(Boolean);status.error=errors.length?errors.join(' | '):null;return status;});function update(dt,{heroState='idle',enemyState='enemyIdle',heroSpeed=0,enemySpeed=0}={}){hero.update(dt,heroState,heroSpeed);enemy.update(dt,enemyState,enemySpeed);}return{status,ready,update};}
