import * as THREE from 'three';

function production(mesh,lod=0){mesh.castShadow=true;mesh.receiveShadow=true;mesh.userData.productionShell=true;mesh.userData.lodLevel=lod;return mesh;}
function tapered(top,bottom,length,depth,segments=22){const levels=[{y:length*.5,w:top,d:depth},{y:length*.12,w:top*.94,d:depth*.98},{y:-length*.34,w:bottom*1.06,d:depth*.9},{y:-length*.5,w:bottom,d:depth*.84}],pos=[],idx=[];for(let j=0;j<levels.length;j++)for(let i=0;i<segments;i++){const a=i/segments*Math.PI*2,l=levels[j];pos.push(Math.cos(a)*l.w,l.y,Math.sin(a)*l.d);}for(let j=0;j<levels.length-1;j++)for(let i=0;i<segments;i++){const n=(i+1)%segments,a=j*segments+i,b=j*segments+n,c=(j+1)*segments+n,d=(j+1)*segments+i;idx.push(a,b,d,b,c,d);}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.setIndex(idx);g.computeVertexNormals();return g;}
function plate(points,depth=.08){const s=new THREE.Shape();s.moveTo(...points[0]);for(let i=1;i<points.length;i++)s.lineTo(...points[i]);s.closePath();const g=new THREE.ExtrudeGeometry(s,{depth,steps:1,bevelEnabled:true,bevelSegments:3,bevelSize:.018,bevelThickness:.018});g.translate(0,0,-depth*.5);g.computeVertexNormals();return g;}
function maceHeadGeometry(){const g=new THREE.IcosahedronGeometry(.29,2),p=g.attributes.position;for(let i=0;i<p.count;i++){const v=new THREE.Vector3().fromBufferAttribute(p,i),n=v.clone().normalize(),ridge=1+Math.pow(Math.abs(n.x*n.y*n.z)*5.2,.55)*.15;p.setXYZ(i,v.x*ridge,v.y*ridge,v.z*ridge);}p.needsUpdate=true;g.computeVertexNormals();return g;}
export function addWardenProductionDetails(rig,M){
  const {spine,armL,armR,forearmL,forearmR,handR}=rig.bones;
  for(const [arm,forearm,s] of [[armL,forearmL,-1],[armR,forearmR,1]]){
    if(arm){const upper=production(new THREE.Mesh(tapered(.195,.15,.62,.18,24),M.dark));upper.name=`Warden${s<0?'Left':'Right'}ArmShell`;upper.position.set(0,-.28,.01);arm.add(upper);}
    if(forearm){const vambrace=production(new THREE.Mesh(tapered(.155,.115,.43,.145,22),M.accent),1);vambrace.name=`Warden${s<0?'Left':'Right'}Vambrace`;vambrace.position.set(0,-.21,.015);forearm.add(vambrace);const ridge=production(new THREE.Mesh(plate([[-.055,-.17],[-.09,.05],[0,.2],[.09,.05],[.055,-.17]],.035),M.steel),1);ridge.name='WardenVambraceRidge';ridge.position.set(0,-.19,.145);forearm.add(ridge);}
  }
  const back=production(new THREE.Mesh(plate([[-.38,-.28],[-.49,.06],[-.29,.38],[0,.48],[.29,.38],[.49,.06],[.38,-.28],[0,-.39]],.095),M.steel),1);back.name='WardenBackplate';back.position.set(0,.24,-.34);back.rotation.y=Math.PI;spine.add(back);
  for(const s of [-1,1]){const fin=production(new THREE.Mesh(plate([[-.035,-.24],[.085,-.06],[.065,.32],[-.065,.32],[-.085,-.06]],.045),M.accent),1);fin.name='WardenBackFin';fin.position.set(.25*s,.5,-.37);fin.rotation.z=-s*.18;spine.add(fin);}
  if(handR){const weapon=new THREE.Group();weapon.name='WardenMace';weapon.position.set(.03,-.02,.02);weapon.rotation.set(.05,0,.1);handR.add(weapon);const shaft=production(new THREE.Mesh(tapered(.05,.042,1.15,.05,16),M.steel));shaft.position.y=-.48;weapon.add(shaft);const head=production(new THREE.Mesh(maceHeadGeometry(),M.accent));head.name='WardenMaceHead';head.position.y=-1.08;weapon.add(head);for(let i=0;i<6;i++){const spike=production(new THREE.Mesh(new THREE.ConeGeometry(.052,.23,10),M.accent),1),a=i/6*Math.PI*2;spike.position.set(Math.cos(a)*.25,-1.08,Math.sin(a)*.25);spike.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),new THREE.Vector3(Math.cos(a),0,Math.sin(a)));weapon.add(spike);}const endSpike=production(new THREE.Mesh(new THREE.ConeGeometry(.06,.28,12),M.accent),1);endSpike.position.set(0,-1.36,0);endSpike.rotation.x=Math.PI;weapon.add(endSpike);}
}
