import * as THREE from 'three';

export class EnemyCombatBrain{
  constructor({body,rig,animation,vfx,audio,targetBody}){this.body=body;this.rig=rig;this.animation=animation;this.vfx=vfx;this.audio=audio;this.targetBody=targetBody;this.state='idle';this.timer=0;this.cooldown=.9;this.telegraph=0;this.hitCommitted=false;this.lastDistance=Infinity;this.tmp=new THREE.Vector3();this.forward=new THREE.Vector3();this.lateral=new THREE.Vector3();this.flank=Math.random()<.5?-1:1;this.behaviorClock=1.5;this.windupDuration=.62;this.attackDamage=16;this.attackReach=3.2;this.attackSpeed=4.6;this.pattern='crush';}
  update(dt){const enemyPos=this.body.position,targetPos=this.targetBody.position;this.tmp.subVectors(targetPos,enemyPos);const d=this.tmp.length();this.lastDistance=d;this.timer=Math.max(0,this.timer-dt);this.cooldown=Math.max(0,this.cooldown-dt);this.behaviorClock-=dt;if(this.behaviorClock<=0){this.behaviorClock=1.2+Math.random()*1.7;if(Math.random()<.52)this.flank*=-1;}if(this.state==='dead'){this.body.desiredVelocity.set(0,0,0);return{damage:0};}
    if(this.state==='windup'){this.body.desiredVelocity.set(0,0,0);this.telegraph=1-this.timer/this.windupDuration;if(this.timer<=0){this.state='strike';this.timer=this.pattern==='crush'?.23:.17;this.hitCommitted=false;this.animation.trigger('enemyAttack',{fade:.03});this.vfx?.groundBurst(enemyPos.clone(),{color:this.pattern==='crush'?0xff5e42:0xff9b54,radius:this.pattern==='crush'?1.25:.92});this.audio?.playWhoosh(enemyPos.clone().add(new THREE.Vector3(0,1.5,0)),this.pattern==='crush'?.9:.7);}return{damage:0,telegraph:this.telegraph,pattern:this.pattern};}
    if(this.state==='strike'){this.forward.copy(this.tmp).setY(0);if(this.forward.lengthSq()>.001)this.forward.normalize();this.body.desiredVelocity.copy(this.forward).multiplyScalar(this.attackSpeed);if(!this.hitCommitted&&this.timer<(this.pattern==='crush'?.14:.1)){this.hitCommitted=true;const predicted=targetPos.clone().addScaledVector(this.targetBody.velocity||new THREE.Vector3(),.045),hit=enemyPos.distanceTo(predicted)<this.attackReach;if(hit){this.vfx?.impact(predicted.clone().add(new THREE.Vector3(0,1.25,0)),{color:this.pattern==='crush'?0xff6b55:0xffb36a,count:this.pattern==='crush'?22:14,scale:this.pattern==='crush'?1.15:.9});this.audio?.playImpact(predicted,this.pattern==='crush'?1:.82);}return{damage:hit?this.attackDamage:0,pattern:this.pattern};}if(this.timer<=0){this.state='recover';this.timer=this.pattern==='crush'?.62:.38;this.body.desiredVelocity.set(0,0,0);}return{damage:0,pattern:this.pattern};}
    if(this.state==='recover'){this.body.desiredVelocity.set(0,0,0);if(this.timer<=0){this.state='chase';this.cooldown=.65+Math.random()*.55;}return{damage:0};}
    if(d<this.attackReach+.3&&this.cooldown<=0){this.pattern=Math.random()<.62?'crush':'cleave';this.windupDuration=this.pattern==='crush'?.68:.46;this.attackDamage=this.pattern==='crush'?18:12;this.attackReach=this.pattern==='crush'?3.25:3.0;this.attackSpeed=this.pattern==='crush'?4.8:5.35;this.state='windup';this.timer=this.windupDuration;this.telegraph=0;this.body.desiredVelocity.set(0,0,0);return{damage:0,telegraph:0,pattern:this.pattern};}
    if(d<17){this.state='chase';this.forward.copy(this.tmp).setY(0);if(this.forward.lengthSq()>.001)this.forward.normalize();this.lateral.set(-this.forward.z,0,this.forward.x).multiplyScalar(this.flank);const preferred=3.7,rangeError=d-preferred,forwardWeight=THREE.MathUtils.clamp(rangeError*.55,-1,1),strafeWeight=d<8?.5:.18;this.body.desiredVelocity.copy(this.forward).multiplyScalar(forwardWeight*(d>8?4.2:3.1)).addScaledVector(this.lateral,strafeWeight*2.15);if(d<2.65)this.body.desiredVelocity.addScaledVector(this.forward,-2.3);}else{this.state='idle';this.body.desiredVelocity.set(0,0,0);}return{damage:0};}
  kill(){this.state='dead';this.body.desiredVelocity.set(0,0,0);this.animation.trigger('enemyDeath',{fade:.08});}
}
