import * as THREE from 'three';
import { makeStoneMaterial, makeCrystalMaterial } from './materials.js';
import { installHybridEnvironment } from './hybridEnvironment.js';
import { createGrassClumpGeometry, createFernGeometry, createBroadleafGroundGeometry, createShrubGeometry, createMossPatchGeometry, createFlowerGeometry, createTreeSpeciesLibrary } from './foliage.js';

function brokenWallGeometry(){
  const s=new THREE.Shape();s.moveTo(-.72,0);s.lineTo(.7,0);s.lineTo(.67,.86);s.lineTo(.48,1.18);s.lineTo(.18,1.45);s.lineTo(-.08,1.45);s.lineTo(-.36,1.32);s.lineTo(-.7,1.02);s.closePath();const g=new THREE.ExtrudeGeometry(s,{depth:.48,steps:1,bevelEnabled:true,bevelSegments:2,bevelSize:.055,bevelThickness:.055,curveSegments:3});g.translate(0,0,-.24);g.computeVertexNormals();return g;
}
function combatLane(x,z){const r=Math.hypot(x,z);return r<4.25||(Math.abs(x)<1.65&&z>-13.5&&z<13.5);}
function clusteredPoint(rng,index,spread=2.6){const centers=[[-8.8,-5.5],[8.5,-5.8],[-10.4,3.8],[10.6,4.1],[-6.3,10.2],[6.7,10.6],[-13.2,-.5],[13.1,.4],[-4.8,-12.1],[5.2,-12.3]],c=centers[index%centers.length],a=rng()*Math.PI*2,r=Math.sqrt(rng())*spread;return[c[0]+Math.cos(a)*r,c[1]+Math.sin(a)*r];}
function pathEdgePoint(rng,index){const z=-14.5+(index%18)*(29/17)+(rng()-.5)*.9,meander=Math.sin(z*.055)*1.05+Math.sin(z*.018+1.7)*.62,side=index%2?-1:1,offset=2.25+rng()*1.55;return[meander+side*offset,z];}
function configureInstances(mesh,count){mesh.count=count;mesh.instanceMatrix.needsUpdate=true;if(mesh.instanceColor)mesh.instanceColor.needsUpdate=true;mesh.frustumCulled=true;mesh.receiveShadow=true;return mesh;}
function plantMaterial(emissive=0x15240f,intensity=.18){return new THREE.MeshLambertMaterial({color:0xffffff,side:THREE.DoubleSide,emissive,emissiveIntensity:intensity,vertexColors:false});}

function buildHeroTreeGrove({scene,heightFn}){
  const root=new THREE.Group();root.name='HeroTreeGrove';scene.add(root);const kits=createTreeSpeciesLibrary(),placements=[[-15.5,-9.5,0,1.18],[-11.8,-14.2,2,1.03],[-6.6,-16.4,1,.96],[6.9,-16.2,2,1.03],[12.1,-13.9,0,1.1],[15.7,-9.1,1,.98],[-17.1,-2.6,1,1.02],[17.0,-2.1,2,1.08],[-16.1,6.1,0,1.12],[16.4,6.3,0,1.04],[-12.2,12.0,2,1.06],[-6.3,15.2,0,.98],[6.5,15.0,1,1.02],[12.4,11.8,2,1.08]];
  const bySpecies=kits.map(()=>[]);for(const p of placements)bySpecies[p[2]].push(p);for(let si=0;si<kits.length;si++){const kit=kits[si],list=bySpecies[si],trunks=new THREE.InstancedMesh(kit.trunk,kit.trunkMaterial,list.length),crowns=new THREE.InstancedMesh(kit.nearCrown,kit.nearMaterial,list.length);trunks.castShadow=trunks.receiveShadow=true;crowns.castShadow=crowns.receiveShadow=true;list.forEach(([x,z,_species,scale],i)=>{const y=heightFn(x,z),yaw=(i*.91+si*1.17)%6.283,q=new THREE.Quaternion().setFromEuler(new THREE.Euler(0,yaw,0)),s=scale*(.96+(i%3)*.035);trunks.setMatrixAt(i,new THREE.Matrix4().compose(new THREE.Vector3(x,y,z),q,new THREE.Vector3(s,s,s)));crowns.setMatrixAt(i,new THREE.Matrix4().compose(new THREE.Vector3(x,y+kit.crownY*s,z),q,new THREE.Vector3(s*(.95+(i%2)*.09),s*(.97+(i%3)*.035),s*(.95+(i%2)*.09))));});trunks.instanceMatrix.needsUpdate=crowns.instanceMatrix.needsUpdate=true;root.add(trunks,crowns);}
  if(typeof window!=='undefined')window.__GAUNTLET_HERO_TREES__={target:'high-end OSRS/07Scape',ready:true,count:placements.length,species:kits.map(k=>k.id),placement:'hand-composed arena perimeter',crownArchitecture:'high-density lobed broadleaf + layered conifer boughs'};return placements.length;
}

export function buildRuinArena({scene,physics,heightFn,rng}){
  const root=new THREE.Group();root.name='RuinArena';scene.add(root);const stone=makeStoneMaterial(),wallGeo=brokenWallGeometry(),columnGeo=new THREE.CylinderGeometry(.48,.64,1,18,5),slabGeo=new THREE.BoxGeometry(1,1,1,4,1,4),rubbleGeo=new THREE.DodecahedronGeometry(.35,1);
  for(let i=0;i<18;i++){const a=i/18*Math.PI*2,r=10.7+(i%3)*.72,x=Math.cos(a)*r,z=Math.sin(a)*r,y=heightFn(x,z),g=new THREE.Group();g.position.set(x,y,z);g.rotation.y=-a+(rng()-.5)*.28;if(i%5===0){const h=2.7+rng()*1.45,col=new THREE.Mesh(columnGeo,stone);col.scale.set(.82,h,.82);col.position.y=h*.5;col.rotation.z=(rng()-.5)*.055;col.castShadow=col.receiveShadow=true;g.add(col);const cap=new THREE.Mesh(new THREE.CylinderGeometry(.68,.62,.22,18),stone);cap.position.y=h+.08;cap.castShadow=true;g.add(cap);physics.addBox(new THREE.Vector3(x,y+h*.5,z),new THREE.Vector3(.52,h*.5,.52));}else{const wall=new THREE.Mesh(wallGeo,stone);const sx=.78+rng()*.58,sy=.9+rng()*.7;wall.scale.set(sx,sy,.82+rng()*.28);wall.rotation.z=(rng()-.5)*.075;wall.castShadow=wall.receiveShadow=true;g.add(wall);for(let j=0;j<2;j++){const rubble=new THREE.Mesh(rubbleGeo,stone);const rs=.45+rng()*.75;rubble.scale.set(rs*1.3,rs*.65,rs);rubble.position.set((rng()-.5)*1.15,.12+rs*.16,(rng()-.5)*.75);rubble.rotation.set(rng(),rng()*6.28,rng());rubble.castShadow=true;g.add(rubble);}physics.addBox(new THREE.Vector3(x,y+.68*sy,z),new THREE.Vector3(.72*sx,.7*sy,.42));}root.add(g);}
  for(let i=0;i<16;i++){const a=i/16*Math.PI*2,r=7.55+(i%2)*.34,x=Math.cos(a)*r,z=Math.sin(a)*r,y=heightFn(x,z),slab=new THREE.Mesh(slabGeo,stone);slab.scale.set(1.45,.1,.72);slab.position.set(x,y+.02,z);slab.rotation.set((rng()-.5)*.02,-a+(rng()-.5)*.1,(rng()-.5)*.018);slab.receiveShadow=true;root.add(slab);}
  for(const a of[0,Math.PI]){const r=11.35,x=Math.cos(a)*r,z=Math.sin(a)*r,y=heightFn(x,z),gate=new THREE.Group();gate.position.set(x,y,z);gate.rotation.y=-a;for(const s of[-1,1]){const p=new THREE.Mesh(new THREE.CylinderGeometry(.38,.52,3.5,18,4),stone);p.position.set(s*1.22,1.75,0);p.rotation.z=s*.025;p.castShadow=p.receiveShadow=true;gate.add(p);}const arch=new THREE.Mesh(new THREE.TorusGeometry(1.22,.3,14,42,Math.PI),stone);arch.position.y=3.44;arch.rotation.z=Math.PI;arch.rotation.y=Math.PI/2;arch.castShadow=true;gate.add(arch);root.add(gate);}
  const rune=new THREE.Mesh(new THREE.RingGeometry(2.4,2.47,96),new THREE.MeshBasicMaterial({color:0x52cce8,transparent:true,opacity:.16,blending:THREE.AdditiveBlending,depthWrite:false,toneMapped:false}));rune.rotation.x=-Math.PI/2;rune.position.set(0,heightFn(0,0)+.035,0);root.add(rune);const heroTreeCount=buildHeroTreeGrove({scene,heightFn});if(!scene.getObjectByName('GroundDetail'))buildGroundDetail({scene,heightFn,rng,heroTreeCount});installHybridEnvironment({scene,heightFn}).catch(error=>console.error('Hybrid authored environment rejected:',error));return root;
}

export function buildGroundDetail({scene,heightFn,rng,heroTreeCount=0}){
  const root=new THREE.Group();root.name='GroundDetail';scene.add(root);const grassGeo=createGrassClumpGeometry({blades:16,height:.42,width:.032}),fernGeo=createFernGeometry(),broadGeo=createBroadleafGroundGeometry(),shrubGeo=createShrubGeometry(),mossGeo=createMossPatchGeometry(),flowerGeo=createFlowerGeometry();
  const grass=new THREE.InstancedMesh(grassGeo,plantMaterial(0x17260f,.2),700),ferns=new THREE.InstancedMesh(fernGeo,plantMaterial(0x142511,.22),220),broadleaf=new THREE.InstancedMesh(broadGeo,plantMaterial(0x182813,.2),190),shrubs=new THREE.InstancedMesh(shrubGeo,plantMaterial(0x14230f,.22),110),moss=new THREE.InstancedMesh(mossGeo,plantMaterial(0x1d3019,.23),165),flowers=new THREE.InstancedMesh(flowerGeo,plantMaterial(0x2c2411,.15),145);
  const palettes={grass:[0x78934c,0x5d7f42,0x879d58],fern:[0x55794a,0x40683e,0x698751],broad:[0x69864d,0x4e7240,0x80995b],shrub:[0x526f3e,0x658249,0x405f3b],moss:[0x4d6946,0x5e774e,0x3d593b],flower:[0xf0dc8c,0xe2bf61,0xc5d9ee,0xd9c0e7,0xc7d79d]};
  function fill(mesh,target,kind,spread,scaleMin,scaleMax,edgeBias=false){let n=0,tries=0;while(n<target&&tries<target*8){const[x,z]=edgeBias?pathEdgePoint(rng,tries+(kind==='shrub'?3:7)):clusteredPoint(rng,tries+(kind==='fern'?2:kind==='flower'?5:kind==='broad'?7:kind==='moss'?4:0),spread),r=Math.hypot(x,z);tries++;if(r>18.5||combatLane(x,z))continue;const y=heightFn(x,z),s=scaleMin+rng()*(scaleMax-scaleMin),tilt=(rng()-.5)*.04,q=new THREE.Quaternion().setFromEuler(new THREE.Euler(tilt,rng()*Math.PI*2,-tilt*.6));mesh.setMatrixAt(n,new THREE.Matrix4().compose(new THREE.Vector3(x,y+(kind==='moss'?.008:.011),z),q,new THREE.Vector3(s,s*(.97+rng()*.06),s)));mesh.setColorAt(n,new THREE.Color(palettes[kind][Math.floor(rng()*palettes[kind].length)]));n++;}configureInstances(mesh,n);return n;}
  const counts={grass:fill(grass,650,'grass',3.2,.55,.96),fern:fill(ferns,184,'fern',2.75,.65,1.0),broadleaf:fill(broadleaf,160,'broad',2.5,.64,.96),shrubs:fill(shrubs,90,'shrub',2.1,.55,.86,true),moss:fill(moss,142,'moss',2.4,.48,.8,true),flowers:fill(flowers,122,'flower',2.25,.65,1.0)};grass.castShadow=ferns.castShadow=broadleaf.castShadow=shrubs.castShadow=moss.castShadow=flowers.castShadow=false;root.add(grass,ferns,broadleaf,shrubs,moss,flowers);

  const heroBeds=[[-5.7,6.0],[5.8,6.1],[-7.2,3.0],[7.3,3.2]],heroMeshes={fern:new THREE.InstancedMesh(fernGeo,ferns.material,48),broad:new THREE.InstancedMesh(broadGeo,broadleaf.material,36),shrub:new THREE.InstancedMesh(shrubGeo,shrubs.material,24),moss:new THREE.InstancedMesh(mossGeo,moss.material,24),flower:new THREE.InstancedMesh(flowerGeo,flowers.material,40)};
  function fillHero(mesh,count,kind,sMin,sMax){for(let i=0;i<count;i++){const c=heroBeds[i%heroBeds.length],ring=.3+(i%6)*.17,a=i*2.399963+kind.length*.41,x=c[0]+Math.cos(a)*ring,z=c[1]+Math.sin(a)*ring,y=heightFn(x,z),s=sMin+(i%5)/4*(sMax-sMin),q=new THREE.Quaternion().setFromEuler(new THREE.Euler((i%3-1)*.025,a*.37,(i%2?1:-1)*.02));mesh.setMatrixAt(i,new THREE.Matrix4().compose(new THREE.Vector3(x,y+(kind==='moss'?.007:.011),z),q,new THREE.Vector3(s,s*(.96+(i%3)*.025),s)));mesh.setColorAt(i,new THREE.Color(palettes[kind][i%palettes[kind].length]));}configureInstances(mesh,count);mesh.castShadow=false;root.add(mesh);return count;}
  const heroPlants={fern:fillHero(heroMeshes.fern,48,'fern',.82,1.12),broadleaf:fillHero(heroMeshes.broad,36,'broad',.78,1.05),shrubs:fillHero(heroMeshes.shrub,24,'shrub',.7,.94),moss:fillHero(heroMeshes.moss,24,'moss',.62,.88),flowers:fillHero(heroMeshes.flower,40,'flower',.8,1.08)};

  const pebbleGeo=new THREE.DodecahedronGeometry(.09,1),pebbles=new THREE.InstancedMesh(pebbleGeo,new THREE.MeshStandardMaterial({color:0x726957,roughness:.96,metalness:0}),220);let pi=0;for(let i=0;i<360&&pi<210;i++){const a=rng()*Math.PI*2,r=4.1+rng()*14.1,x=Math.cos(a)*r,z=Math.sin(a)*r;if(combatLane(x,z)&&rng()>.32)continue;const y=heightFn(x,z),s=.35+rng()*.9;pebbles.setMatrixAt(pi++,new THREE.Matrix4().compose(new THREE.Vector3(x,y+.028*s,z),new THREE.Quaternion().setFromEuler(new THREE.Euler(rng(),rng()*6.28,rng())),new THREE.Vector3(s*1.2,s*.48,s)));}configureInstances(pebbles,pi);root.add(pebbles);counts.pebbles=pi;
  const pathStoneGeo=new THREE.DodecahedronGeometry(.12,0),pathStoneMat=new THREE.MeshStandardMaterial({color:0xffffff,roughness:.97,metalness:0}),pathStones=new THREE.InstancedMesh(pathStoneGeo,pathStoneMat,360);let si=0;for(let i=0;i<420&&si<335;i++){const z=-15+rng()*30,meander=Math.sin(z*.055)*1.05+Math.sin(z*.018+1.7)*.62,x=meander+(rng()-.5)*3.1;if(Math.hypot(x,z)<3.8&&rng()>.64)continue;const y=heightFn(x,z),s=.5+rng()*.82,q=new THREE.Quaternion().setFromEuler(new THREE.Euler((rng()-.5)*.12,rng()*6.28,(rng()-.5)*.1));pathStones.setMatrixAt(si,new THREE.Matrix4().compose(new THREE.Vector3(x,y+.02,z),q,new THREE.Vector3(s*1.42,s*.24,s)));pathStones.setColorAt(si,new THREE.Color([0x827a68,0x6f6a5d,0x8c826f,0x696254,0x77705f][i%5]));si++;}configureInstances(pathStones,si);pathStones.castShadow=false;root.add(pathStones);counts.pathStones=si;
  const scatteredPlants=counts.grass+counts.fern+counts.broadleaf+counts.shrubs+counts.moss+counts.flowers,heroPlantCount=Object.values(heroPlants).reduce((a,b)=>a+b,0),totalPlants=scatteredPlants+heroPlantCount,status={target:'high-end OSRS/07Scape',ready:true,accepted:false,placement:'clustered-authored-density',combatLaneClear:true,clusters:10,pathEdgeClusters:18,heroPlantBeds:heroBeds.length,heroPlants,heroPlantCount,plantFamilies:['grass','fern','broadleaf','shrub','moss','flower'],counts,totalPlants,heroTrees:heroTreeCount,pathStones:si,foliagePresentation:'rounded tapered-leaf silhouettes + moss cushions + restrained scale + fixed hero beds',treeCrownArchitecture:'high-density lobed broadleaf + layered conifer boughs',note:'Structural density only; screenshot critic controls visual acceptance.'};if(typeof window!=='undefined')window.__GAUNTLET_GROUND_DETAIL__=status;return root;
}

export function buildCrystalField({scene,heightFn,rng}){const root=new THREE.Group();root.name='CrystalField';scene.add(root);const material=makeCrystalMaterial(),geo=new THREE.OctahedronGeometry(.28,2);for(let i=0;i<12;i++){const a=rng()*Math.PI*2,r=17+rng()*30,x=Math.cos(a)*r,z=Math.sin(a)*r,s=.75+rng()*.65,c=new THREE.Mesh(geo,material);c.scale.set(s*.62,s*(2.4+rng()*1.9),s*.62);c.position.set(x,heightFn(x,z)+.48*s,z);c.rotation.set((rng()-.5)*.14,rng()*6.28,(rng()-.5)*.22);c.castShadow=true;root.add(c);if(i<4){const l=new THREE.PointLight(0x4acff2,.72,7,2);l.position.copy(c.position).add(new THREE.Vector3(0,.8,0));root.add(l);}}return root;}
