import * as THREE from 'three';
import { EffectComposer } from 'three/addons/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/addons/postprocessing/RenderPass.js';
import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';
import { SMAAPass } from 'three/addons/postprocessing/SMAAPass.js';
import { OutputPass } from 'three/addons/postprocessing/OutputPass.js';

export function createRenderingPipeline(renderer,scene,camera){
  scene.background=new THREE.Color(0x0b1b24);if(scene.fog){scene.fog.color.set(0x10252a);if('density'in scene.fog)scene.fog.density=.0058;}
  renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1;renderer.outputColorSpace=THREE.SRGBColorSpace;
  let resolutionScale=Math.min(devicePixelRatio,1.5);renderer.setPixelRatio(resolutionScale);
  const composer=new EffectComposer(renderer),renderPass=new RenderPass(scene,camera),bloom=new UnrealBloomPass(new THREE.Vector2(innerWidth,innerHeight),.44,.5,.84),smaa=new SMAAPass(innerWidth*renderer.getPixelRatio(),innerHeight*renderer.getPixelRatio()),output=new OutputPass();bloom.threshold=.82;bloom.strength=.34;bloom.radius=.45;composer.addPass(renderPass);composer.addPass(bloom);composer.addPass(smaa);composer.addPass(output);
  const exposure={target:1,value:1};let sceneBudgetApplied=false,emaMs=16.67,adjustClock=0,metricClock=0;
  function resize(w,h){composer.setSize(w,h);smaa.setSize(w*renderer.getPixelRatio(),h*renderer.getPixelRatio());}
  function applySceneBudget(){if(sceneBudgetApplied)return;sceneBudgetApplied=true;let pointLights=0;scene.traverse(o=>{if(o.isPointLight){pointLights++;if(pointLights>5)o.visible=false;}const mats=Array.isArray(o.material)?o.material:o.material?[o.material]:[];for(const m of mats){if('transmission'in m&&m.transmission>0){m.transmission=0;m.opacity=1;m.transparent=false;m.needsUpdate=true;}}});}
  function govern(dt){emaMs=emaMs*.94+dt*1000*.06;adjustClock+=dt;metricClock+=dt;if(adjustClock>2.4){adjustClock=0;let next=resolutionScale;if(emaMs>28)next=Math.max(.9,resolutionScale-.22);else if(emaMs>21)next=Math.max(.9,resolutionScale-.12);else if(emaMs<15.4)next=Math.min(Math.min(devicePixelRatio,1.5),resolutionScale+.08);if(Math.abs(next-resolutionScale)>.035){resolutionScale=+next.toFixed(2);renderer.setPixelRatio(resolutionScale);resize(innerWidth,innerHeight);}}
    if(metricClock>1){metricClock=0;const r=renderer.info.render,m=renderer.info.memory;window.__GAUNTLET_METRICS__={frameMs:+emaMs.toFixed(2),fps:+(1000/Math.max(1,emaMs)).toFixed(1),resolutionScale,drawCalls:r.calls,triangles:r.triangles,lines:r.lines,points:r.points,textures:m.textures,geometries:m.geometries};}}
  return{composer,bloom,update(dt,{combat=0,darkness=.5}={}){applySceneBudget();govern(dt);exposure.target=THREE.MathUtils.clamp(.94+darkness*.12-combat*.02,.92,1.06);exposure.value=THREE.MathUtils.damp(exposure.value,exposure.target,2.6,dt);renderer.toneMappingExposure=exposure.value;bloom.strength=THREE.MathUtils.damp(bloom.strength,.3+combat*.1,5,dt);},resize,getMetrics:()=>window.__GAUNTLET_METRICS__||null};
}

function addDuskSky(scene){const material=new THREE.ShaderMaterial({side:THREE.BackSide,depthWrite:false,fog:false,toneMapped:true,vertexShader:`varying vec3 vDir;void main(){vDir=normalize(position);gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.0);}`,fragmentShader:`varying vec3 vDir;void main(){float h=clamp(vDir.y*.5+.5,0.,1.);vec3 horizon=vec3(.09,.19,.22);vec3 mid=vec3(.035,.085,.13);vec3 zenith=vec3(.009,.024,.052);vec3 c=mix(horizon,mid,smoothstep(.3,.62,h));c=mix(c,zenith,smoothstep(.58,1.,h));float glow=pow(max(0.,dot(normalize(vDir),normalize(vec3(-.55,.18,.5)))),20.);c+=vec3(.28,.12,.045)*glow*.42;gl_FragColor=vec4(c,1.);}`});const sky=new THREE.Mesh(new THREE.SphereGeometry(250,24,12),material);sky.renderOrder=-1000;scene.add(sky);return sky;}

export function configureHeroLightRig(scene){const sky=addDuskSky(scene),hemi=new THREE.HemisphereLight(0x8fb9c8,0x251c16,1.18);scene.add(hemi);const sun=new THREE.DirectionalLight(0xffd6a0,3.85);sun.position.set(-28,38,18);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-42;sun.shadow.camera.right=42;sun.shadow.camera.top=42;sun.shadow.camera.bottom=-42;sun.shadow.camera.near=.5;sun.shadow.camera.far=105;sun.shadow.bias=-.00018;sun.shadow.normalBias=.035;scene.add(sun);const rim=new THREE.DirectionalLight(0x78b8ee,1.65);rim.position.set(22,16,-30);scene.add(rim);const fill=new THREE.PointLight(0x4f8698,.68,26,2);fill.position.set(0,7,5);scene.add(fill);return{sky,hemi,sun,rim,fill};}

export function createContactShadow(scene){const tex=document.createElement('canvas');tex.width=tex.height=128;const c=tex.getContext('2d'),g=c.createRadialGradient(64,64,4,64,64,60);g.addColorStop(0,'rgba(0,0,0,.68)');g.addColorStop(.45,'rgba(0,0,0,.34)');g.addColorStop(1,'rgba(0,0,0,0)');c.fillStyle=g;c.fillRect(0,0,128,128);const map=new THREE.CanvasTexture(tex),mat=new THREE.MeshBasicMaterial({map,transparent:true,depthWrite:false,opacity:.58,toneMapped:false}),mesh=new THREE.Mesh(new THREE.PlaneGeometry(2.3,2.3),mat);mesh.rotation.x=-Math.PI/2;mesh.renderOrder=2;scene.add(mesh);return{mesh,update(position,heightFn,scale=1){mesh.position.set(position.x,heightFn(position.x,position.z)+.025,position.z);mesh.scale.setScalar(scale);}};}
