import * as THREE from 'three';

export class CombatVFX{
  constructor(scene,camera){this.scene=scene;this.camera=camera;this.fx=[];this.impulse=0;this.hitStop=0;this.sparkGeo=new THREE.IcosahedronGeometry(.035,0);this.sparkBase=new THREE.MeshBasicMaterial({color:0xffd89b,transparent:true,opacity:.82,blending:THREE.AdditiveBlending,depthWrite:false,toneMapped:false});}
  slash({origin,direction,color=0x72dfff,length=2.25}){const g=new THREE.Group(),mat=new THREE.MeshBasicMaterial({color,transparent:true,opacity:.42,side:THREE.DoubleSide,blending:THREE.AdditiveBlending,depthWrite:false,toneMapped:false});const arc=new THREE.Mesh(new THREE.RingGeometry(length*.68,length,72,1,-.95,1.9),mat);arc.rotation.x=Math.PI/2;g.add(arc);const core=new THREE.Mesh(new THREE.RingGeometry(length*.86,length*.95,72,1,-.9,1.78),mat.clone());core.material.color.setHex(0xe7fbff);core.material.opacity=.68;core.rotation.x=Math.PI/2;g.add(core);g.position.copy(origin);g.lookAt(origin.clone().add(direction));this.scene.add(g);this.fx.push({o:g,life:.16,max:.16,kind:'fadeScale'});this.cameraImpulse(.12);this.hitStop=.022;}
  impact(position,{color=0xffc676,count=18,scale=1}={}){for(let i=0;i<count;i++){const m=new THREE.Mesh(this.sparkGeo,this.sparkBase.clone());m.material.color.setHex(i%5===0?0xfff4da:color);m.position.copy(position);this.scene.add(m);const v=new THREE.Vector3((Math.random()-.5)*4.7,Math.random()*4.1+.8,(Math.random()-.5)*4.7).multiplyScalar(scale);this.fx.push({o:m,v,life:.25+Math.random()*.18,max:.43,kind:'particle'});}const ring=this.#ring(position,color,.12,.2);this.fx.push({o:ring,life:.18,max:.18,kind:'ring'});const light=new THREE.PointLight(color,2.4*scale,5.5*scale,2);light.position.copy(position);this.scene.add(light);this.fx.push({o:light,life:.075,max:.075,kind:'light'});this.cameraImpulse(.18*scale);this.hitStop=Math.max(this.hitStop,.032*scale);}
  groundBurst(position,{color=0x54cfee,radius=3.0}={}){const ring=this.#ring(position,color,.28,.38,true);ring.material.opacity=.48;this.fx.push({o:ring,life:.42,max:.42,kind:'burst',radius});for(let i=0;i<2;i++){const r=this.#ring(position,color,.44+i*.14,.49+i*.14,true);r.material.opacity=.22;this.fx.push({o:r,life:.38+i*.05,max:.48,kind:'burst',radius:radius*(.5+i*.22)});}this.cameraImpulse(.18);}
  rift(position,{color=0x4bc9ed,radius=3.3}={}){this.groundBurst(position,{color,radius});const mat=new THREE.MeshBasicMaterial({color,transparent:true,opacity:.3,blending:THREE.AdditiveBlending,depthWrite:false,toneMapped:false,side:THREE.DoubleSide});for(let i=0;i<5;i++){const a=i/5*Math.PI*2+.25,r=.65+Math.random()*radius*.58,h=1.7+Math.random()*2.7;const beam=new THREE.Mesh(new THREE.PlaneGeometry(.055+Math.random()*.045,h),mat.clone());beam.position.set(position.x+Math.cos(a)*r,position.y+h*.5,position.z+Math.sin(a)*r);beam.lookAt(this.camera.position.x,beam.position.y,this.camera.position.z);this.scene.add(beam);this.fx.push({o:beam,life:.34+Math.random()*.18,max:.52,kind:'beam'});}const light=new THREE.PointLight(color,2.8,7.5,2);light.position.copy(position).add(new THREE.Vector3(0,1.1,0));this.scene.add(light);this.fx.push({o:light,life:.2,max:.2,kind:'light'});this.cameraImpulse(.22);}
  createTelegraph(position,{color=0xff563d,radius=2.5}={}){const mat=new THREE.MeshBasicMaterial({color,transparent:true,opacity:.12,side:THREE.DoubleSide,blending:THREE.AdditiveBlending,depthWrite:false,toneMapped:false});const disc=new THREE.Mesh(new THREE.CircleGeometry(radius,64),mat);disc.rotation.x=-Math.PI/2;disc.position.copy(position).add(new THREE.Vector3(0,.035,0));const outline=new THREE.Mesh(new THREE.RingGeometry(radius*.95,radius,64),mat.clone());outline.material.opacity=.62;outline.rotation.x=-Math.PI/2;disc.add(outline);this.scene.add(disc);return{mesh:disc,set(progress){const p=THREE.MathUtils.clamp(progress,0,1);disc.material.opacity=.07+.14*p;outline.material.opacity=.32+.5*p;outline.scale.setScalar(.82+.18*p);},dispose:()=>{this.scene.remove(disc);disc.geometry.dispose();disc.material.dispose();outline.geometry.dispose();outline.material.dispose();}};}
  cameraImpulse(amount){this.impulse=Math.max(this.impulse,amount);}
  update(dt){const scaled=this.hitStop>0?0:dt;this.hitStop=Math.max(0,this.hitStop-dt);this.impulse=THREE.MathUtils.damp(this.impulse,0,14,dt);for(let i=this.fx.length-1;i>=0;i--){const f=this.fx[i];f.life-=dt;const t=Math.max(0,f.life/f.max);if(f.kind==='particle'){f.v.y-=12*dt;f.o.position.addScaledVector(f.v,dt);f.o.scale.setScalar(t*.7+.18);f.o.material.opacity=t*.8;}else if(f.kind==='ring'){f.o.scale.setScalar(1+(1-t)*4.5);f.o.material.opacity=t*.5;}else if(f.kind==='burst'){const s=1+(1-t)*f.radius*1.55;f.o.scale.setScalar(s);f.o.material.opacity=t*.42;}else if(f.kind==='beam'){f.o.scale.x=.7+t*.3;f.o.material.opacity=t*.3;}else if(f.kind==='light'){f.o.intensity*=Math.pow(t,.45);}else{f.o.scale.setScalar(1+(1-t)*.22);f.o.traverse(x=>{if(x.material)x.material.opacity*=.9;});}if(f.life<=0){this.scene.remove(f.o);f.o.traverse?.(x=>{x.geometry?.dispose?.();x.material?.dispose?.();});this.fx.splice(i,1);}}return scaled;}
  #ring(position,color,inner,outer,ground=false){const m=new THREE.Mesh(new THREE.RingGeometry(inner,outer,64),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.52,side:THREE.DoubleSide,blending:THREE.AdditiveBlending,depthWrite:false,toneMapped:false}));m.position.copy(position);if(ground){m.rotation.x=-Math.PI/2;m.position.y+=.04;}else m.lookAt(this.camera.position);this.scene.add(m);return m;}
}
