import * as THREE from 'three';

export class CombatVFX{
  constructor(scene,camera){this.scene=scene;this.camera=camera;this.fx=[];this.impulse=0;this.hitStop=0;this.sparkGeo=new THREE.IcosahedronGeometry(.035,0);this.sparkBase=new THREE.MeshBasicMaterial({color:0xffd89b,transparent:true,opacity:.82,blending:THREE.AdditiveBlending,depthWrite:false,toneMapped:false});}
  slash({origin,direction,color=0x66d8f0,length=2.05}){
    const g=new THREE.Group(),side=new THREE.Vector3().crossVectors(direction.clone().normalize(),new THREE.Vector3(0,1,0)).normalize();
    const curve=new THREE.CatmullRomCurve3([
      origin.clone().addScaledVector(side,-.82).add(new THREE.Vector3(0,-.22,0)),
      origin.clone().addScaledVector(direction,.48).addScaledVector(side,-.18).add(new THREE.Vector3(0,.05,0)),
      origin.clone().addScaledVector(direction,1.0).addScaledVector(side,.5).add(new THREE.Vector3(0,.28,0)),
      origin.clone().addScaledVector(direction,1.35).addScaledVector(side,.9).add(new THREE.Vector3(0,.12,0))
    ]);
    const trailMat=new THREE.MeshBasicMaterial({color,transparent:true,opacity:.48,blending:THREE.AdditiveBlending,depthWrite:false,toneMapped:false});
    const trail=new THREE.Mesh(new THREE.TubeGeometry(curve,28,.025,6,false),trailMat);g.add(trail);
    const core=new THREE.Mesh(new THREE.TubeGeometry(curve,28,.008,5,false),trailMat.clone());core.material.color.setHex(0xe6fbff);core.material.opacity=.76;g.add(core);
    this.scene.add(g);this.fx.push({o:g,life:.145,max:.145,kind:'trail'});this.cameraImpulse(.09);this.hitStop=.018;
  }
  impact(position,{color=0xffbd6c,count=16,scale=1}={}){for(let i=0;i<count;i++){const m=new THREE.Mesh(this.sparkGeo,this.sparkBase.clone());m.material.color.setHex(i%5===0?0xfff4da:color);m.position.copy(position);this.scene.add(m);const v=new THREE.Vector3((Math.random()-.5)*4.3,Math.random()*3.7+.7,(Math.random()-.5)*4.3).multiplyScalar(scale);this.fx.push({o:m,v,life:.22+Math.random()*.16,max:.38,kind:'particle'});}const ring=this.#ring(position,color,.08,.14);this.fx.push({o:ring,life:.14,max:.14,kind:'ring'});const light=new THREE.PointLight(color,1.8*scale,4.5*scale,2);light.position.copy(position);this.scene.add(light);this.fx.push({o:light,life:.06,max:.06,kind:'light'});this.cameraImpulse(.15*scale);this.hitStop=Math.max(this.hitStop,.028*scale);}
  groundBurst(position,{color=0x45bedb,radius=3.0}={}){for(let i=0;i<3;i++){const r=this.#ring(position,color,.32+i*.12,.355+i*.12,true);r.material.opacity=.18-i*.025;this.fx.push({o:r,life:.48+i*.06,max:.54+i*.06,kind:'burst',radius:radius*(.45+i*.21)});}this.cameraImpulse(.12);}
  rift(position,{color=0x42c6e9,radius=3.2}={}){
    this.groundBurst(position,{color,radius});
    const runeMat=new THREE.MeshBasicMaterial({color,transparent:true,opacity:.28,blending:THREE.AdditiveBlending,depthWrite:false,toneMapped:false});
    for(let i=0;i<7;i++){const a=i/7*Math.PI*2+.14,radiusBand=1.05+(i%2)*.52,p0=position.clone().add(new THREE.Vector3(Math.cos(a)*radiusBand,.055,Math.sin(a)*radiusBand)),p1=p0.clone().add(new THREE.Vector3(Math.cos(a)*.48,.04,Math.sin(a)*.48));const line=new THREE.Mesh(new THREE.CylinderGeometry(.018,.018,p0.distanceTo(p1),5),runeMat.clone());line.position.copy(p0).lerp(p1,.5);line.quaternion.setFromUnitVectors(new THREE.Vector3(0,1,0),p1.clone().sub(p0).normalize());this.scene.add(line);this.fx.push({o:line,life:.46,max:.46,kind:'rune'});}
    for(let i=0;i<4;i++){const a=i/4*Math.PI*2+.45,r=.8+Math.random()*radius*.46,h=1.25+Math.random()*1.45;const beam=new THREE.Mesh(new THREE.CylinderGeometry(.018,.05,h,6,1,true),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.18,blending:THREE.AdditiveBlending,depthWrite:false,toneMapped:false}));beam.position.set(position.x+Math.cos(a)*r,position.y+h*.5,position.z+Math.sin(a)*r);this.scene.add(beam);this.fx.push({o:beam,life:.32+Math.random()*.12,max:.44,kind:'beam'});}
    const light=new THREE.PointLight(color,1.9,6,2);light.position.copy(position).add(new THREE.Vector3(0,.7,0));this.scene.add(light);this.fx.push({o:light,life:.16,max:.16,kind:'light'});this.cameraImpulse(.16);
  }
  createTelegraph(position,{color=0xff563d,radius=2.5}={}){const mat=new THREE.MeshBasicMaterial({color,transparent:true,opacity:.12,side:THREE.DoubleSide,blending:THREE.AdditiveBlending,depthWrite:false,toneMapped:false});const disc=new THREE.Mesh(new THREE.CircleGeometry(radius,64),mat);disc.rotation.x=-Math.PI/2;disc.position.copy(position).add(new THREE.Vector3(0,.035,0));const outline=new THREE.Mesh(new THREE.RingGeometry(radius*.95,radius,64),mat.clone());outline.material.opacity=.62;outline.rotation.x=-Math.PI/2;disc.add(outline);this.scene.add(disc);return{mesh:disc,set(progress){const p=THREE.MathUtils.clamp(progress,0,1);disc.material.opacity=.07+.14*p;outline.material.opacity=.32+.5*p;outline.scale.setScalar(.82+.18*p);},dispose:()=>{this.scene.remove(disc);disc.geometry.dispose();disc.material.dispose();outline.geometry.dispose();outline.material.dispose();}};}
  cameraImpulse(amount){this.impulse=Math.max(this.impulse,amount);}
  update(dt){const scaled=this.hitStop>0?0:dt;this.hitStop=Math.max(0,this.hitStop-dt);this.impulse=THREE.MathUtils.damp(this.impulse,0,14,dt);for(let i=this.fx.length-1;i>=0;i--){const f=this.fx[i];f.life-=dt;const t=Math.max(0,f.life/f.max);if(f.kind==='particle'){f.v.y-=12*dt;f.o.position.addScaledVector(f.v,dt);f.o.scale.setScalar(t*.7+.18);f.o.material.opacity=t*.8;}else if(f.kind==='ring'){f.o.scale.setScalar(1+(1-t)*3.2);f.o.material.opacity=t*.38;}else if(f.kind==='burst'){const s=1+(1-t)*f.radius*1.35;f.o.scale.setScalar(s);f.o.material.opacity=t*.22;}else if(f.kind==='beam'){f.o.scale.set(.8+t*.2,1,.8+t*.2);f.o.material.opacity=t*.18;}else if(f.kind==='rune'){f.o.material.opacity=t*.28;}else if(f.kind==='light'){f.o.intensity*=Math.pow(t,.45);}else if(f.kind==='trail'){f.o.scale.setScalar(1);f.o.traverse(x=>{if(x.material)x.material.opacity*=.8;});}if(f.life<=0){this.scene.remove(f.o);f.o.traverse?.(x=>{x.geometry?.dispose?.();x.material?.dispose?.();});this.fx.splice(i,1);}}return scaled;}
  #ring(position,color,inner,outer,ground=false){const m=new THREE.Mesh(new THREE.RingGeometry(inner,outer,64),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.42,side:THREE.DoubleSide,blending:THREE.AdditiveBlending,depthWrite:false,toneMapped:false}));m.position.copy(position);if(ground){m.rotation.x=-Math.PI/2;m.position.y+=.04;}else m.lookAt(this.camera.position);this.scene.add(m);return m;}
}
