import * as THREE from 'three';

export class CombatVFX{
  constructor(scene,camera){this.scene=scene;this.camera=camera;this.fx=[];this.impulse=0;this.hitStop=0;this.sparkGeo=new THREE.IcosahedronGeometry(.042,0);this.sparkBase=new THREE.MeshBasicMaterial({color:0xffd89b,transparent:true,blending:THREE.AdditiveBlending,depthWrite:false,toneMapped:false});}
  slash({origin,direction,color=0x8de9ff,length=2.45}){const g=new THREE.Group(),mat=new THREE.MeshBasicMaterial({color,transparent:true,opacity:.96,side:THREE.DoubleSide,blending:THREE.AdditiveBlending,depthWrite:false,toneMapped:false});const arc=new THREE.Mesh(new THREE.RingGeometry(.72,length,64,1,-1.15,2.3),mat);arc.rotation.x=Math.PI/2;g.add(arc);const core=new THREE.Mesh(new THREE.RingGeometry(.92,length*.82,64,1,-1.02,2.05),mat.clone());core.material.color.setHex(0xe8fbff);core.material.opacity=.54;core.rotation.x=Math.PI/2;g.add(core);g.position.copy(origin);g.lookAt(origin.clone().add(direction));this.scene.add(g);this.fx.push({o:g,life:.2,max:.2,kind:'fadeScale'});this.cameraImpulse(.15);this.hitStop=.026;}
  impact(position,{color=0xffcf7c,count=18,scale=1}={}){for(let i=0;i<count;i++){const m=new THREE.Mesh(this.sparkGeo,this.sparkBase.clone());m.material.color.setHex(i%4===0?0xffffff:color);m.position.copy(position);this.scene.add(m);const v=new THREE.Vector3((Math.random()-.5)*5.5,Math.random()*4.8+1,(Math.random()-.5)*5.5).multiplyScalar(scale);this.fx.push({o:m,v,life:.32+Math.random()*.2,max:.52,kind:'particle'});}const ring=this.#ring(position,color,.12,.23);this.fx.push({o:ring,life:.25,max:.25,kind:'ring'});const light=new THREE.PointLight(color,4.5*scale,7*scale,2);light.position.copy(position);this.scene.add(light);this.fx.push({o:light,life:.1,max:.1,kind:'light'});this.cameraImpulse(.22*scale);this.hitStop=Math.max(this.hitStop,.04*scale);}
  groundBurst(position,{color=0x5edcff,radius=3.2}={}){const ring=this.#ring(position,color,.28,.42,true);this.fx.push({o:ring,life:.58,max:.58,kind:'burst',radius});for(let i=0;i<3;i++){const r=this.#ring(position,color,.42+i*.12,.47+i*.12,true);r.material.opacity=.35;this.fx.push({o:r,life:.44+i*.06,max:.55,kind:'burst',radius:radius*(.55+i*.18)});}this.cameraImpulse(.25);}
  rift(position,{color=0x58dcff,radius=3.5}={}){this.groundBurst(position,{color,radius});const mat=new THREE.MeshBasicMaterial({color,transparent:true,opacity:.7,blending:THREE.AdditiveBlending,depthWrite:false,toneMapped:false,side:THREE.DoubleSide});for(let i=0;i<7;i++){const a=i/7*Math.PI*2,r=.5+Math.random()*radius*.65,h=1.8+Math.random()*3.5;const beam=new THREE.Mesh(new THREE.PlaneGeometry(.09+Math.random()*.08,h),mat.clone());beam.position.set(position.x+Math.cos(a)*r,position.y+h*.5,position.z+Math.sin(a)*r);beam.lookAt(this.camera.position.x,beam.position.y,this.camera.position.z);this.scene.add(beam);this.fx.push({o:beam,life:.42+Math.random()*.28,max:.7,kind:'beam'});}const light=new THREE.PointLight(color,5.5,10,2);light.position.copy(position).add(new THREE.Vector3(0,1.2,0));this.scene.add(light);this.fx.push({o:light,life:.32,max:.32,kind:'light'});this.cameraImpulse(.32);}
  createTelegraph(position,{color=0xff563d,radius=2.5}={}){const mat=new THREE.MeshBasicMaterial({color,transparent:true,opacity:.18,side:THREE.DoubleSide,blending:THREE.AdditiveBlending,depthWrite:false,toneMapped:false});const disc=new THREE.Mesh(new THREE.CircleGeometry(radius,64),mat);disc.rotation.x=-Math.PI/2;disc.position.copy(position).add(new THREE.Vector3(0,.035,0));const outline=new THREE.Mesh(new THREE.RingGeometry(radius*.94,radius,64),mat.clone());outline.material.opacity=.75;outline.rotation.x=-Math.PI/2;disc.add(outline);this.scene.add(disc);return{mesh:disc,set(progress){const p=THREE.MathUtils.clamp(progress,0,1);disc.material.opacity=.1+.22*p;outline.material.opacity=.35+.6*p;outline.scale.setScalar(.75+.25*p);},dispose:()=>{this.scene.remove(disc);disc.geometry.dispose();disc.material.dispose();outline.geometry.dispose();outline.material.dispose();}};}
  cameraImpulse(amount){this.impulse=Math.max(this.impulse,amount);}
  update(dt){const scaled=this.hitStop>0?0:dt;this.hitStop=Math.max(0,this.hitStop-dt);this.impulse=THREE.MathUtils.damp(this.impulse,0,13,dt);for(let i=this.fx.length-1;i>=0;i--){const f=this.fx[i];f.life-=dt;const t=Math.max(0,f.life/f.max);if(f.kind==='particle'){f.v.y-=13*dt;f.o.position.addScaledVector(f.v,dt);f.o.scale.setScalar(t*.85+.15);f.o.material.opacity=t;}else if(f.kind==='ring'){f.o.scale.setScalar(1+(1-t)*7);f.o.material.opacity=t;}else if(f.kind==='burst'){const s=1+(1-t)*f.radius*2;f.o.scale.setScalar(s);f.o.material.opacity=t*.7;}else if(f.kind==='beam'){f.o.scale.x=.65+t*.5;f.o.material.opacity=t*.72;}else if(f.kind==='light'){f.o.intensity*=Math.pow(t,.35);}else{f.o.scale.setScalar(1+(1-t)*.85);f.o.traverse(x=>{if(x.material)x.material.opacity=t;});}if(f.life<=0){this.scene.remove(f.o);f.o.traverse?.(x=>{x.geometry?.dispose?.();x.material?.dispose?.();});this.fx.splice(i,1);}}return scaled;}
  #ring(position,color,inner,outer,ground=false){const m=new THREE.Mesh(new THREE.RingGeometry(inner,outer,64),new THREE.MeshBasicMaterial({color,transparent:true,opacity:.9,side:THREE.DoubleSide,blending:THREE.AdditiveBlending,depthWrite:false,toneMapped:false}));m.position.copy(position);if(ground){m.rotation.x=-Math.PI/2;m.position.y+=.04;}else m.lookAt(this.camera.position);this.scene.add(m);return m;}
}
