import './styles.css';
import * as THREE from 'three';
import { EffectComposer } from 'three/addons/postprocessing/EffectComposer.js';
import { RenderPass } from 'three/addons/postprocessing/RenderPass.js';
import { UnrealBloomPass } from 'three/addons/postprocessing/UnrealBloomPass.js';
import { OutputPass } from 'three/addons/postprocessing/OutputPass.js';
import { PhysicsWorld, terrainNormalFromHeight } from './systems/physics.js';
import { AnimationGraph, authorEnemyClips } from './systems/animation.js';
import { createLayeredTerrain } from './systems/terrain.js';
import { createVolumetricAtmosphere } from './systems/atmosphere.js';
import { CombatVFX } from './systems/vfx.js';
import { createHeroRig, createEnemyRig, createProceduralClips } from './systems/rig.js';

const app=document.querySelector('#app');
const scene=new THREE.Scene();scene.background=new THREE.Color(0x071015);scene.fog=new THREE.FogExp2(0x0a1518,.008);
const camera=new THREE.PerspectiveCamera(55,innerWidth/innerHeight,.08,420);
const renderer=new THREE.WebGLRenderer({antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setSize(innerWidth,innerHeight);renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.12;renderer.outputColorSpace=THREE.SRGBColorSpace;app.appendChild(renderer.domElement);
const composer=new EffectComposer(renderer);composer.addPass(new RenderPass(scene,camera));composer.addPass(new UnrealBloomPass(new THREE.Vector2(innerWidth,innerHeight),.48,.52,.76));composer.addPass(new OutputPass());

const heightFn=(x,z)=>Math.sin(x*.075)*1.65+Math.cos(z*.058)*1.12+Math.sin((x+z)*.13)*.48-Math.exp(-(x*x+z*z)/430)*1.2;
const normalFn=(x,z,out)=>terrainNormalFromHeight(heightFn,x,z,out);
const {mesh:terrain}=createLayeredTerrain({heightFn});scene.add(terrain);

const hemi=new THREE.HemisphereLight(0x7ca9c1,0x241b15,1.35);scene.add(hemi);const sun=new THREE.DirectionalLight(0xffe0b2,5.4);sun.position.set(-24,35,12);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-44;sun.shadow.camera.right=44;sun.shadow.camera.top=44;sun.shadow.camera.bottom=-44;sun.shadow.bias=-.0002;scene.add(sun);const moon=new THREE.DirectionalLight(0x79bfff,1.7);moon.position.set(20,13,-26);scene.add(moon);

const rockMat=new THREE.MeshStandardMaterial({color:0x626b69,roughness:.83,metalness:.06});const barkMat=new THREE.MeshStandardMaterial({color:0x3b2d26,roughness:.94});const leafMat=new THREE.MeshStandardMaterial({color:0x294237,roughness:.84,side:THREE.DoubleSide});
let seed=712367;const rng=()=>((seed=(seed*48271)%2147483647)/2147483647);
const physics=new PhysicsWorld({terrainHeight:heightFn,terrainNormal:normalFn});
for(let i=0;i<110;i++){const a=rng()*Math.PI*2,r=14+rng()*66,x=Math.cos(a)*r,z=Math.sin(a)*r;if(rng()<.55){const g=new THREE.Group();const trunk=new THREE.Mesh(new THREE.CylinderGeometry(.28,.52,4.5+rng()*4,8),barkMat);trunk.position.y=2.2;trunk.castShadow=true;g.add(trunk);for(let j=0;j<3;j++){const crown=new THREE.Mesh(new THREE.ConeGeometry(1.8+rng(),3.2+rng()*2,9),leafMat);crown.position.y=4.2+j*1.35;crown.rotation.y=rng()*6.28;crown.castShadow=true;g.add(crown);}g.position.set(x,heightFn(x,z),z);scene.add(g);physics.addSphere(new THREE.Vector3(x,heightFn(x,z)+2.2,z),.6);}else{const rock=new THREE.Mesh(new THREE.DodecahedronGeometry(.6+rng()*1.5,1),rockMat);rock.scale.set(1+rng(),.7+rng(),1+rng());rock.position.set(x,heightFn(x,z)+.35,z);rock.rotation.set(rng(),rng()*6.2,rng());rock.castShadow=rock.receiveShadow=true;scene.add(rock);physics.addSphere(rock.position,Math.max(rock.scale.x,rock.scale.z)*.7);}}
for(let i=0;i<18;i++){const a=i/18*Math.PI*2,x=Math.cos(a)*10,z=Math.sin(a)*10;const h=2.5+rng()*2,m=new THREE.Mesh(new THREE.BoxGeometry(1.5,h,1.25),rockMat);m.position.set(x,heightFn(x,z)+h*.5,z);m.rotation.y=-a+(rng()-.5)*.4;m.castShadow=m.receiveShadow=true;scene.add(m);physics.addBox(m.position,new THREE.Vector3(.75,h*.5,.625));}

const crystalMat=new THREE.MeshStandardMaterial({color:0x56d8ff,emissive:0x159bd5,emissiveIntensity:3.6,roughness:.16,metalness:.22});for(let i=0;i<14;i++){const a=rng()*6.28,r=12+rng()*28,x=Math.cos(a)*r,z=Math.sin(a)*r,c=new THREE.Mesh(new THREE.OctahedronGeometry(.18+rng()*.34,0),crystalMat);c.scale.y=2.5+rng()*4;c.position.set(x,heightFn(x,z)+.6,z);scene.add(c);const l=new THREE.PointLight(0x4fdcff,.7,5,2);l.position.copy(c.position);scene.add(l);}

const heroRig=createHeroRig();const hero=heroRig.group;hero.position.set(0,heightFn(0,4),4);scene.add(hero);const heroBody=physics.createCharacter(hero.position,{radius:.44,height:1.9});const heroAnim=new AnimationGraph({root:hero,clips:createProceduralClips(heroRig),terrainHeight:heightFn,terrainNormal:normalFn});heroAnim.trigger('idle',{loop:true});
const enemyRig=createEnemyRig();const enemy=enemyRig.group;enemy.position.set(0,heightFn(0,-5),-5);scene.add(enemy);const enemyBody=physics.createCharacter(enemy.position,{radius:.58,height:2.2});const enemyAnim=new AnimationGraph({root:enemy,clips:authorEnemyClips(enemy),terrainHeight:heightFn,terrainNormal:normalFn});enemyAnim.trigger('enemyIdle',{loop:true});

const atmosphere=createVolumetricAtmosphere({scene,camera,layers:20});const vfx=new CombatVFX(scene,camera);
const dustGeo=new THREE.BufferGeometry(),dustCount=700,dustPos=new Float32Array(dustCount*3);for(let i=0;i<dustCount;i++){dustPos[i*3]=(rng()-.5)*110;dustPos[i*3+1]=rng()*18;dustPos[i*3+2]=(rng()-.5)*110;}dustGeo.setAttribute('position',new THREE.BufferAttribute(dustPos,3));const dust=new THREE.Points(dustGeo,new THREE.PointsMaterial({color:0xb8e4d8,size:.035,transparent:true,opacity:.36,depthWrite:false,blending:THREE.AdditiveBlending}));scene.add(dust);

const keys=new Set();let yaw=0,pitch=.3,dragging=false,lastX=0,lastY=0,stamina=100,hp=100,enemyHp=100,riftT=0,guardT=0,attackCooldown=0,enemyAttackT=0,time=0,attackWindow=false;
addEventListener('keydown',e=>{keys.add(e.code);if(e.code==='Digit1'&&attackCooldown<=0){attackCooldown=.62;attackWindow=true;heroAnim.trigger('attack');vfx.slash({origin:hero.position.clone().add(new THREE.Vector3(0,1.25,0)),direction:new THREE.Vector3(Math.sin(hero.rotation.y),0,Math.cos(hero.rotation.y))});}if(e.code==='Digit2'&&riftT<=0){riftT=4;vfx.groundBurst(hero.position.clone());if(hero.position.distanceTo(enemy.position)<8){enemyHp=Math.max(0,enemyHp-28);vfx.impact(enemy.position.clone().add(new THREE.Vector3(0,1.5,0)),{color:0x9cecff,count:22,scale:1.2});}}if(e.code==='Digit3'&&guardT<=0)guardT=3;if(e.code==='Space'&&stamina>=22){stamina-=22;heroAnim.trigger('dodge');heroBody.velocity.addScaledVector(new THREE.Vector3(Math.sin(hero.rotation.y),0,Math.cos(hero.rotation.y)),9);}});addEventListener('keyup',e=>keys.delete(e.code));renderer.domElement.addEventListener('contextmenu',e=>e.preventDefault());renderer.domElement.addEventListener('pointerdown',e=>{if(e.button===2){dragging=true;lastX=e.clientX;lastY=e.clientY;}});addEventListener('pointerup',()=>dragging=false);addEventListener('pointermove',e=>{if(!dragging)return;yaw-=(e.clientX-lastX)*.005;pitch=THREE.MathUtils.clamp(pitch-(e.clientY-lastY)*.004,-.05,.65);lastX=e.clientX;lastY=e.clientY;});

const fwd=new THREE.Vector3(),right=new THREE.Vector3(),move=new THREE.Vector3(),tmp=new THREE.Vector3(),camTarget=new THREE.Vector3(),camDesired=new THREE.Vector3();
function update(dt){time+=dt;const simDt=vfx.update(dt);riftT=Math.max(0,riftT-dt);guardT=Math.max(0,guardT-dt);attackCooldown=Math.max(0,attackCooldown-dt);enemyAttackT=Math.max(0,enemyAttackT-dt);dust.rotation.y+=dt*.006;atmosphere.update(dt,time);
  fwd.set(Math.sin(yaw),0,-Math.cos(yaw));right.set(Math.cos(yaw),0,Math.sin(yaw));move.set(0,0,0);if(keys.has('KeyW'))move.add(fwd);if(keys.has('KeyS'))move.sub(fwd);if(keys.has('KeyD'))move.add(right);if(keys.has('KeyA'))move.sub(right);if(move.lengthSq()>0)move.normalize();const sprint=keys.has('ShiftLeft')&&stamina>1,speed=sprint?8.2:4.7;heroBody.desiredVelocity.copy(move).multiplyScalar(speed);if(move.lengthSq()>0){const targetYaw=Math.atan2(move.x,move.z);hero.rotation.y=THREE.MathUtils.lerp(hero.rotation.y,targetYaw,1-Math.exp(-dt*12));if(sprint)stamina=Math.max(0,stamina-dt*18);else stamina=Math.min(100,stamina+dt*9);}else stamina=Math.min(100,stamina+dt*13);
  physics.stepCharacter(heroBody,simDt);hero.position.copy(heroBody.position);heroAnim.setLocomotion({speed:heroBody.velocity.length(),grounded:heroBody.grounded});const rootDelta=heroAnim.update(simDt,heroBody.desiredVelocity,fwd);hero.position.add(new THREE.Vector3(rootDelta.x,0,rootDelta.z).applyAxisAngle(new THREE.Vector3(0,1,0),hero.rotation.y));heroBody.position.copy(hero.position);
  if(attackWindow&&attackCooldown<.36&&attackCooldown>.28){attackWindow=false;if(hero.position.distanceTo(enemy.position)<3.25){enemyHp=Math.max(0,enemyHp-16);vfx.impact(enemy.position.clone().add(new THREE.Vector3(0,1.4,0)),{count:18});}}
  if(enemyHp>0){tmp.subVectors(hero.position,enemy.position);const d=tmp.length();enemy.lookAt(hero.position.x,enemy.position.y,hero.position.z);if(d>2.8&&d<14){enemyBody.desiredVelocity.copy(tmp.setY(0).normalize()).multiplyScalar(2.8);}else enemyBody.desiredVelocity.set(0,0,0);physics.stepCharacter(enemyBody,simDt);enemy.position.copy(enemyBody.position);if(d<3.1&&enemyAttackT<=0){enemyAttackT=1.25;enemyAnim.trigger('enemyAttack');setTimeout(()=>{if(enemyHp>0&&enemy.position.distanceTo(hero.position)<3.4){hp=Math.max(0,hp-(guardT>0?5:14));vfx.impact(hero.position.clone().add(new THREE.Vector3(0,1.2,0)),{color:0xff6b55,count:12});}},360);}if(enemyAttackT<=0)enemyAnim.trigger('enemyIdle',{loop:true});enemyAnim.setLocomotion({speed:enemyBody.velocity.length(),combat:true,grounded:enemyBody.grounded});enemyAnim.update(simDt,enemyBody.desiredVelocity,tmp);}else enemy.visible=false;
  camTarget.copy(hero.position).add(new THREE.Vector3(0,1.65,0));const dist=6.3,cp=Math.cos(pitch),sp=Math.sin(pitch);camDesired.set(Math.sin(yaw)*cp*dist,2.2+sp*dist,Math.cos(yaw)*cp*dist).add(camTarget);if(vfx.impulse>0)camDesired.add(new THREE.Vector3((Math.random()-.5)*vfx.impulse,(Math.random()-.5)*vfx.impulse,(Math.random()-.5)*vfx.impulse));camera.position.lerp(camDesired,1-Math.exp(-dt*11));camera.lookAt(camTarget);
  document.querySelector('#hp').style.width=`${hp}%`;document.querySelector('#stamina').style.width=`${stamina}%`;document.querySelector('#enemyHp').style.width=`${enemyHp}%`;document.querySelector('#targetCard').classList.toggle('hidden',hero.position.distanceTo(enemy.position)>18||enemyHp<=0);document.querySelector('#status').textContent=guardT>0?'GUARDING':sprint?'SPRINTING':'READY';document.querySelector('#cd1').textContent=attackCooldown>0?attackCooldown.toFixed(1):'';document.querySelector('#cd2').textContent=riftT>0?riftT.toFixed(1):'';document.querySelector('#cd3').textContent=guardT>0?guardT.toFixed(1):'';
}
const clock=new THREE.Clock();function loop(){requestAnimationFrame(loop);update(Math.min(clock.getDelta(),.033));composer.render();}loop();addEventListener('resize',()=>{camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();renderer.setSize(innerWidth,innerHeight);composer.setSize(innerWidth,innerHeight);});
