import { chromium } from 'playwright';
import fs from 'node:fs/promises';

await fs.mkdir('artifacts/frames',{recursive:true});
await fs.mkdir('artifacts/video',{recursive:true});
const browser=await chromium.launch({headless:true});
const context=await browser.newContext({viewport:{width:1920,height:1080},recordVideo:{dir:'artifacts/video',size:{width:1920,height:1080}}});
const page=await context.newPage();
const errors=[];
page.on('pageerror',e=>errors.push(`pageerror: ${e.message}`));
page.on('console',m=>{if(m.type()==='error')errors.push(`console: ${m.text()}`);});
await page.goto('http://127.0.0.1:4173',{waitUntil:'networkidle'});
await page.waitForTimeout(1800);
await page.screenshot({path:'artifacts/frames/01-idle-1080p.png'});
await page.mouse.click(960,540);
await page.keyboard.down('w');await page.waitForTimeout(900);await page.keyboard.down('Shift');await page.waitForTimeout(900);await page.keyboard.up('Shift');await page.keyboard.up('w');
await page.screenshot({path:'artifacts/frames/02-locomotion-1080p.png'});
await page.keyboard.press('1');await page.waitForTimeout(155);await page.screenshot({path:'artifacts/frames/03-melee-impact-1080p.png'});await page.waitForTimeout(550);
await page.keyboard.press('2');await page.waitForTimeout(120);await page.screenshot({path:'artifacts/frames/04-rift-vfx-1080p.png'});await page.waitForTimeout(900);
await page.keyboard.press('Space');await page.waitForTimeout(160);await page.screenshot({path:'artifacts/frames/05-evade-1080p.png'});await page.waitForTimeout(1200);
await context.close();await browser.close();
if(errors.length){await fs.writeFile('artifacts/browser-errors.txt',errors.join('\n'));throw new Error(`Browser QA found ${errors.length} runtime errors:\n${errors.join('\n')}`);}else await fs.writeFile('artifacts/browser-errors.txt','No pageerror or console.error events captured.\n');
