import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';

const boot=JSON.parse(await fs.readFile('artifacts/boot-metrics.json','utf8'));
const env=boot?.hybridEnvironment||null,ground=boot?.groundDetail||null,terrain=boot?.terrainMaterial||null,streaming=boot?.streamingEnvironment||null;
const failures=[];
if(!env)failures.push('hybrid environment telemetry missing');
else{
  if(env.target!=='high-end OSRS/07Scape')failures.push(`wrong target=${env.target||'missing'}`);if(!env.ready)failures.push('hybrid environment never reached ready state');if(env.error)failures.push(`hybrid environment load error=${env.error}`);
  const assetKeys=Object.keys(env.assets||{});if(assetKeys.length<6)failures.push(`authored environment source variety ${assetKeys.length}<6`);for(const required of['pillar','crates','barrel','brokenWall','doorway','stairs'])if(!env.assets?.[required])failures.push(`missing authored environment source=${required}`);
  if((env.instances||0)<12)failures.push(`authored environment instances ${env.instances||0}<12`);if((env.landmarks||0)<3)failures.push(`authored environment landmarks ${env.landmarks||0}<3`);if((env.suppressedProcedural||0)<2)failures.push(`procedural-overlap suppression ${env.suppressedProcedural||0}<2`);if((env.triangles||0)<1000)failures.push(`authored environment triangle contribution ${env.triangles||0}<1000`);if(!env.texture?.authoredAtlas)failures.push('authored dungeon texture atlas not active');if(env.doorwayHeroPlacement!==false)failures.push('rejected blank doorway hero placement is still active');if(env.centralWallHeroPlacement!==false)failures.push('rejected flat central wall placement is still active');
}
if(!streaming)failures.push('streamed tree telemetry missing');
else{
  if(streaming.target!=='high-end OSRS/07Scape')failures.push(`streaming target=${streaming.target||'missing'}`);const expected=['frontier-oak','silver-ash','ashen-pine'];for(const species of expected)if(!streaming.species?.includes(species))failures.push(`missing tree species=${species}`);
  if((streaming.species?.length||0)<3)failures.push(`tree species variety ${streaming.species?.length||0}<3`);if((streaming.activeChunks||0)<9)failures.push(`active streamed chunks ${streaming.activeChunks||0}<9`);if((streaming.trees||0)<150)failures.push(`streamed tree population ${streaming.trees||0}<150`);if((streaming.nearTreeChunks||0)<5)failures.push(`near-detail tree chunks ${streaming.nearTreeChunks||0}<5`);if((streaming.farTreeChunks||0)<1)failures.push('no far-LOD tree chunks active');if(streaming.lod!=='near-authored-crown / far-simplified-crown')failures.push(`obsolete/unexpected tree LOD strategy=${streaming.lod||'missing'}`);if(streaming.densityProfile!=='grove-clustered-medium')failures.push(`tree density profile=${streaming.densityProfile||'missing'}`);if(streaming.placement!=='deterministic dominant-species groves')failures.push(`tree placement=${streaming.placement||'missing'}`);
}
if(!ground)failures.push('ground-detail telemetry missing');
else{
  if(ground.target!=='high-end OSRS/07Scape')failures.push(`ground target=${ground.target||'missing'}`);if(!ground.ready)failures.push('ground detail not ready');if(ground.placement!=='clustered-authored-density')failures.push(`ground placement=${ground.placement||'missing'}`);if(ground.combatLaneClear!==true)failures.push('combat lane is not protected from undergrowth');if((ground.clusters||0)<8)failures.push(`undergrowth clusters ${ground.clusters||0}<8`);if((ground.pathEdgeClusters||0)<14)failures.push(`authored path-edge clusters ${ground.pathEdgeClusters||0}<14`);if((ground.heroTrees||0)<12)failures.push(`hand-composed hero trees ${ground.heroTrees||0}<12`);if((ground.pathStones||0)<240)failures.push(`path stone breakup ${ground.pathStones||0}<240`);if(!String(ground.foliagePresentation||'').includes('tapered-leaf'))failures.push(`foliage silhouette presentation regressed=${ground.foliagePresentation||'missing'}`);if(!String(ground.foliagePresentation||'').includes('moss cushions'))failures.push('moss presentation is not cushion-based');
  const requiredFamilies=['grass','fern','broadleaf','shrub','moss','flower'];for(const family of requiredFamilies)if(!ground.plantFamilies?.includes(family))failures.push(`near-field plant family missing=${family}`);if((ground.plantFamilies?.length||0)<6)failures.push(`plant-family variety ${ground.plantFamilies?.length||0}<6`);
  const c=ground.counts||{};if((c.grass||0)<500)failures.push(`grass density ${c.grass||0}<500`);if((c.fern||0)<120)failures.push(`fern density ${c.fern||0}<120`);if((c.broadleaf||0)<110)failures.push(`broadleaf density ${c.broadleaf||0}<110`);if((c.shrubs||0)<60)failures.push(`shrub density ${c.shrubs||0}<60`);if((c.moss||0)<90)failures.push(`moss density ${c.moss||0}<90`);if((c.flowers||0)<80)failures.push(`flower density ${c.flowers||0}<80`);if((ground.totalPlants||0)<1150)failures.push(`total near-field plants ${ground.totalPlants||0}<1150`);
}
if(!terrain)failures.push('terrain-material telemetry missing');
else{
  if(terrain.target!=='high-end OSRS/07Scape')failures.push(`terrain target=${terrain.target||'missing'}`);if(!terrain.ready)failures.push('terrain material not ready');for(const layer of['grass','dirt','worn-path','rock','moss'])if(!terrain.layers?.includes(layer))failures.push(`terrain layer missing=${layer}`);if((terrain.textureSize||0)<256)failures.push(`terrain detail texture ${terrain.textureSize||0}<256`);if((terrain.detailRepeat||0)<24)failures.push(`terrain micro repeat ${terrain.detailRepeat||0}<24`);if((terrain.microHeightMeters||0)<.03)failures.push(`terrain micro height ${terrain.microHeightMeters||0}<0.03m`);if((terrain.normalStrength||0)<.65)failures.push(`terrain normal strength ${terrain.normalStrength||0}<0.65`);if(!String(terrain.path||'').includes('narrow'))failures.push(`terrain path profile not narrowed: ${terrain.path||'missing'}`);
}
const expectedFrames=['01-idle-1080p.png','02-locomotion-1080p.png','03-melee-impact-1080p.png','04-rift-vfx-1080p.png','05-evade-1080p.png'],hashes=new Set(),frameEvidence=[];
for(const name of expectedFrames){const file=path.join('artifacts','frames',name);try{const data=await fs.readFile(file),hash=crypto.createHash('sha256').update(data).digest('hex');if(data.length<180000)failures.push(`${name} suspiciously low-detail frame=${data.length}B`);if(hashes.has(hash))failures.push(`${name} duplicates another visual evidence frame`);hashes.add(hash);frameEvidence.push({name,bytes:data.length,sha256:hash});}catch{failures.push(`missing rendered frame=${name}`);}}
const result={status:failures.length?'REJECTED':'STRUCTURAL_PASS_VISUAL_REVIEW_REQUIRED',generatedAt:new Date().toISOString(),target:'high-end OSRS/07Scape',environment:env,streamingTrees:streaming,groundDetail:ground,terrainMaterial:terrain,frameEvidence,failures,note:'Iteration-three gate follows direct screenshot rejection. It requires the open hero composition, dominant-species groves, authored crown LODs, six plant families, tapered leaf silhouettes, cushion moss, embedded path breakup and fresh evidence. Structural pass cannot grant art acceptance; direct comparison against the supplied refined OSRS/07Scape target remains mandatory.'};
await fs.writeFile('artifacts/environment-critic.json',JSON.stringify(result,null,2));if(failures.length){console.error(`Environment Gauntlet critic REJECTED:\n- ${failures.join('\n- ')}`);process.exit(1);}console.log(`Iteration-three structural/evidence gate satisfied: ${streaming.species.length} species, ${ground.heroTrees} hero trees, ${ground.plantFamilies.length} plant families, ${ground.totalPlants} plants, ${ground.pathStones} path stones, ${frameEvidence.length} frames. Visual approval remains withheld.`);
